#!/usr/bin/env python3
# Blender OBJ->FBX conversion with J3 manifest (auto-generated by blender_runner.py)
import bpy, sys, os, json, hashlib, traceback

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()

def _s(x):
    if isinstance(x, (bytes, bytearray)):
        return x.decode("utf-8", "replace")
    return str(x)

def main():
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        print("ERROR: no args after '--'", flush=True); sys.exit(1)
    if len(argv) < 3:
        print("ERROR: need input.obj output.fbx manifest.json", flush=True); sys.exit(1)
    input_obj, output_fbx, manifest_path = argv[0], argv[1], argv[2]

    manifest = {"blender_version": bpy.app.version_string,
                "blender_build_commit_time": _s(bpy.app.build_commit_time)}
    unit = bpy.context.scene.unit_settings
    manifest["scene_unit_system"] = unit.system
    manifest["scene_unit_scale"] = unit.scale_length

    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        if hasattr(bpy.ops.wm, "obj_import"):
            bpy.ops.wm.obj_import(filepath=input_obj)
            manifest["import_operator"] = "wm.obj_import"
        else:
            bpy.ops.import_scene.obj(filepath=input_obj)
            manifest["import_operator"] = "import_scene.obj"
        manifest["import_options"] = {"filepath": input_obj}
        print("[BLENDER] OBJ import successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR importing OBJ: {e}", flush=True); traceback.print_exc(); sys.exit(1)

    mesh_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    inventory = []
    for o in mesh_objects:
        mesh = o.data
        inventory.append({
            "name": o.name, "type": o.type,
            "vertices": len(mesh.vertices), "faces": len(mesh.polygons),
            "uv_layers": len(mesh.uv_layers),
            "materials": [m.name for m in mesh.materials if m],
            "bounds": [[round(c, 6) for c in corner] for corner in o.bound_box],
        })
    manifest["objects"] = inventory
    manifest["objects_total"] = len(mesh_objects)
    manifest["materials_total"] = len(bpy.data.materials)
    manifest["images_total"] = len(bpy.data.images)
    manifest["input_obj_hash"] = sha256_file(input_obj)

    output_dir = os.path.dirname(output_fbx)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    try:
        bpy.ops.preferences.addon_enable(module="io_scene_fbx")
    except Exception as e:
        print(f"[BLENDER] WARN io_scene_fbx: {e}", flush=True)
    export_options = dict(
        filepath=output_fbx, use_selection=False, global_scale=1.0,
        apply_unit_scale=True, apply_scale_options='FBX_SCALE_NONE',
        axis_forward='-Z', axis_up='Y',
        object_types={'MESH', 'ARMATURE', 'EMPTY'},
        use_mesh_modifiers=True, mesh_smooth_type='OFF', use_mesh_edges=False,
        use_tspace=False, use_custom_props=False, add_leaf_bones=False,
        primary_bone_axis='Y', secondary_bone_axis='X', armature_nodetype='NULL',
        bake_anim=False, path_mode='AUTO', embed_textures=False, batch_mode='OFF',
    )
    try:
        bpy.ops.export_scene.fbx(**export_options)
        print("[BLENDER] FBX export successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR exporting FBX: {e}", flush=True); traceback.print_exc(); sys.exit(1)
    manifest["export_operator"] = "export_scene.fbx"
    manifest["export_options"] = {
        k: (sorted(v) if isinstance(v, (set, frozenset)) else v) for k, v in export_options.items()}

    if os.path.exists(output_fbx) and os.path.getsize(output_fbx) > 0:
        manifest["output_fbx_hash"] = sha256_file(output_fbx)
        with open(output_fbx, "rb") as fh:
            raw = fh.read(320)
        if raw.startswith(b"Kaydara FBX Binary"):
            manifest["fbx_format"] = "binary"
            manifest["fbx_signature"] = raw.split(b"\x00")[0].decode("ascii", "replace").strip()
            ver_int = None
            for candidate in (7500, 7501, 7400, 7100, 6100):
                if candidate.to_bytes(4, "little") in raw[:320]:
                    ver_int = candidate; break
            manifest["fbx_version_int"] = ver_int
            manifest["fbx_header"] = manifest["fbx_signature"]
            manifest["fbx_version"] = f"FBX binary int={ver_int}" if ver_int else "FBX binary"
        else:
            try:
                first = raw.decode("ascii", "replace").splitlines()[0]
            except Exception:
                first = "<undecodable>"
            manifest["fbx_format"] = "ascii"; manifest["fbx_signature"] = first; manifest["fbx_version"] = first
        print(f"[BLENDER] Output FBX: {os.path.getsize(output_fbx)/(1024*1024):.2f} MB", flush=True)
    else:
        print("[BLENDER] ERROR: empty/missing FBX", flush=True); sys.exit(1)

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print("[BLENDER] CONVERSION_OK", flush=True)
    sys.exit(0)

if __name__ == "__main__":
    main()
