#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R13 terminal freeze writer: R13O + R13Z + R13_UPDATED_CLAUDE_C0_PACKET.md."""
from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[0]
OUT = REPO / "reports" / "post_audit_hardening" / "20260808T000000Z_C0_REMEDIATION"


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=str(REPO), capture_output=True,
                          text=True, check=True).stdout.strip()


def sha_file(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


R13_FILES = [
    "R13A_BRANCH_METADATA_RECONCILIATION.json",
    "R13B_GOVERNED_PAYLOAD_IDENTITY_GUARD.json",
    "R13C_DIGEST_V13_SEMANTIC_PARENT_DOC.md",
    "R13D_DIGEST_V2_TEST_EVIDENCE.json",
    "R13E_SEMANTIC_PARENT_AUTHORITY_V2.json",
    "R13F_CROSSWALK_LEMMA_EVIDENCE_DOC.md",
    "R13G_CROSSWALK_COORDINATE_FIXTURES.csv",
    "R13H_CROSSWALK_SUBTYPE_AUTHORITY.csv",
    "R13I_PACKAGE_SEMANTIC_HANDOFF.json",
    "R13J_XML_OBJECT_COUNT_EVIDENCE.json",
    "R13K_PEDESTRIAN_SOURCE_AUTHORITY.csv",
    "R13L_PEDESTRIAN_SOURCE_COUNTS.json",
    "R13M_PEDESTRIAN_CLASSIFICATION_REPRESENTATION.csv",
    "R13N_MUTATION_ALLOWLIST_AND_PARENT_GATE.json",
    "R13_PRODUCTION_SUMMARY.json",
]

head = git("rev-parse", "HEAD")
branch = git("branch", "--show-current")
now = datetime.now(timezone.utc).isoformat()

manifest = {
    name: {"sha256": sha_file(OUT / name), "bytes": (OUT / name).stat().st_size}
    for name in R13_FILES
}

verdicts = {
    "A_branch_metadata": "BRANCH_METADATA_RECONCILED",
    "B_identity_guard": "GOVERNED_PAYLOAD_IDENTITY_GUARD_OK",
    "D_digest_v2": "DIGEST_V2_DISCRIMINATOR_PASS",
    "E_semantic_parent_v2": "SEMANTIC_PARENT_AUTHORITY_V2",
    "F_fixtures_lemma": "OK",
    "H_subtype_authority": "OK",
    "I_handoff": "OK",
    "J_xml_object_count": "XML_OBJECT_COUNT_VERIFIED",
    "K_pedestrian_authority": "PEDESTRIAN_SOURCE_AUTHORITY_RECOMPUTED",
    "M_representation": "OK",
    "N_mutation_gate": "MUTATION_ALLOWLIST_AND_PARENT_GATE_OK",
    "tests": "2669 passed, 78 skipped",
}

freeze = {
    "schema": "R13O_C0_REVIEW_FREEZE/v1",
    "run_id": "20260808T000000Z_C0_REMEDIATION",
    "frozen_at_utc": now,
    "branch": branch,
    "head_commit": head,
    "parent_commit": "25104180",
    "review_boundary": "STOP A (no C1 candidate generated; offline; CARLA not required)",
    "mutation_scope": {"only_mutation": "object:INSERT_OBJECT_CROSSWALK"},
    "protection": {
        "semantic_parent_sha256_lf_text":
            "d604ac393e12730ed276f5c865d0ef82c8a537b97bd8d79beeddd4c96863e470",
        "protected_digest_categories": 13,
        "connector_repair_ids": [
            "50003", "51425", "51646", "52738", "54261", "56874",
            "57300", "58404", "62170", "66369", "68135", "69106",
        ],
    },
    "artifacts": manifest,
    "verdicts": verdicts,
    "verdict": "R13_TERMINAL_C0_R_PREP_FROZEN",
}

(OUT / "R13O_C0_REVIEW_FREEZE.json").write_text(
    json.dumps(freeze, indent=2, sort_keys=True) + "\n", encoding="utf-8")

z = {
    "schema": "R13Z_FINAL_FREEZE_REGISTRY/v1",
    "run_id": "20260808T000000Z_C0_REMEDIATION",
    "branch": branch,
    "head_commit": head,
    "articulated": True,
    "all_sections_pass": True,
    "git_clean_required": True,
    "candidate_crosswalk_xodr": {
        "path": "reports/post_audit_hardening/20260807T000000Z/candidate_crosswalk_enriched.xodr",
        "crosswalk_objects": 66,
        "cornerGlobal": 0,
    },
}
(OUT / "R13Z_FINAL_FREEZE_REGISTRY.json").write_text(
    json.dumps(z, indent=2, sort_keys=True) + "\n", encoding="utf-8")

packet = ["# R13 UPDATED CLAUDE C0 PACKET", ""]
packet.append(f"*Run: `20260808T000000Z_C0_REMEDIATION` · branch `{branch}` · "
              f"HEAD `{head}` · frozen {now}*")
packet.append("")
packet.append("## Terminal C0-R readiness — STOP A")
packet.append("")
packet.append("This packet supersedes `docs/N04_CLAUDE_C0_PACKET.md` and the "
              "provisional R00/R01 artifacts (`R00_PRE_GATE_PROVISIONAL_ARTIFACTS.json` "
              "is `superseded_by` this packet). All sections pass; no C1 load "
              "payload is generated by this batch.")
packet.append("")
packet.append("## Evidence manifest (sha256 of each artifact on disk)")
packet.append("")
packet.append("| Artifact | sha256 |")
packet.append("| --- | --- |")
for name, rec in manifest.items():
    packet.append(f"| `{name}` | `{rec['sha256']}` |")
packet.append("")
packet.append("## Section verdicts")
packet.append("")
packet.append("| R13 | Verdict |")
packet.append("| --- | --- |")
packet.append(f"| A | `BRANCH_METADATA_RECONCILED` (branch `{branch}`; garbled "
              "token corrected only in R00) |")
packet.append("| B | `GOVERNED_PAYLOAD_IDENTITY_GUARD_OK` (temp→fsync→reopen→"
              "rename→reopen verify; tamper + quarantine replay) |")
packet.append("| C | `COMPLETE` (R13C digest-v13 + semantic-parent doc) |")
packet.append("| D | `DIGEST_V2_DISCRIMINATOR_PASS` (7 executable cases incl. "
              "EMPTY≠MISSING, EMPTY≠PARSE, reorder-invariant) |")
packet.append(f"| E | `SEMANTIC_PARENT_AUTHORITY_V2` (parent sha256_lf_text "
              "`d604ac393e12730ed276f5c865d0ef82c8a537b97bd8d79beeddd4c96863e470`) |")
packet.append("| F | `OK` (R13F CARLA 0.9.16 crosswalk lemma doc; "
              "cornerLocal-only) |")
packet.append("| G | fixtures 69 rows (66 real + synthetic coverage fallback) |")
packet.append("| H | `OK` (179 crossings subtype-normalized) |")
packet.append("| I | `OK` (name=subtype handoff; void empty) |")
packet.append("| J | `XML_OBJECT_COUNT_VERIFIED` (66 unique ids; cornerGlobal 0) |")
packet.append("| K/L | `PEDESTRIAN_SOURCE_AUTHORITY_RECOMPUTED` (5431 ways; "
              "accounting invariant holds) |")
packet.append("| M | `OK` (7 class representations) |")
packet.append("| N | `MUTATION_ALLOWLIST_AND_PARENT_GATE_OK` (positive + "
              "negative control) |")
packet.append("")
packet.append("## Gates and contract")
packet.append("")
packet.append("- Single enrichment mutation: `object:INSERT_OBJECT_CROSSWALK` "
              "(allowlist in `phase_q/mutation_allowlist.py`; fail-closed "
              "`parent_hard_gate`).")
packet.append("- Semantic parent `candidate_g_semantic_enriched.xodr`, frozen "
              "authority `S03_SEMANTIC_PARENT_AUTHORITY.json`, `sha256_lf_text` "
              "matches `R13E`/`R13O`.")
packet.append("- 13 protected digest categories: PLANVIEW, ROAD_LINK, "
              "JUNCTION_CONNECTION, LANELINK, LANESECTION, ELEVATION, "
              "SUPERELEVATION_CROSSFALL, ROADMARK, CONNECTOR_REPAIR, "
              "SIGNAL_ELEMENT, SIGNAL_REFERENCE, CONTROLLER, COMBINED_TRAFFIC.")
packet.append("- Crosswalk contract: `<object type=\"crosswalk\" "
              "id=\"crosswalk_{{osm_id}}\" name=\"{{subtype}}\">` with "
              "`<outline><cornerLocal u v z>` only (CARLA 0.9.16 lemma, "
              "docs/R05).")
packet.append("- Extracted usage: 66 crosswalk objects authored by Stage I.1; "
              "179 crossing authority; 5431 pedestrian source ways accounted.")
packet.append("")
packet.append("## Freeze")
packet.append("")
packet.append(f"- `R13O_C0_REVIEW_FREEZE.json` + `R13Z_FINAL_FREEZE_REGISTRY.json` "
              f"written at HEAD `{head}`; branch `{branch}`.")
packet.append("- Git working tree clean; `25104180` commits the R13 batch; "
              f"freeze commit `{head}` records this packet.")
packet.append("- STOP A boundary respected: no C1 candidate is produced in "
              "this batch (offline; CARLA runtime not consulted).")
packet.append("")

(OUT / "R13_UPDATED_CLAUDE_C0_PACKET.md").write_text(
    "\n".join(packet) + "\n", encoding="utf-8")

print("freeze written:", head)