"""Dependency-free contracts for the optional RoadRunner backend."""

from __future__ import annotations

from .exceptions import RoadRunnerContractError, RoadRunnerGateError
from .gate_matrix import (
    DEFAULT_GATE_MATRIX,
    DEFAULT_GATE_MATRIX_MODEL,
    GateMatrix,
    GateMatrixDecision,
    GateMatrixProfile,
    assert_release_allowed,
    evaluate_gate_matrix,
)
from .grpc_runner import GrpcJob, GrpcResult, run_grpc_job
from .installation import InstallResult, InstallationReport, probe_installation
from .capability_probe import CapabilityReport, CapabilityResult, run_capability_probe
from .matlab_runner import MatlabJob, MatlabResult, run_matlab_job
from .process_runner import (
    RunJobManifest,
    RunResult,
    run_process,
)
from .manifest import artifact_fingerprints, build_run_manifest
from .models import (
    ArtifactRecord,
    ArtifactRole,
    AuthorityClass,
    CapabilityResult,
    ExportOptions,
    ExportProfile,
    GateStatus,
    ImportOptions,
    ImportProfile,
    InstallationCapability,
    MeshXodrAlignmentSummary,
    PathKind,
    PathRef,
    RoadRunnerJobRequest,
    RoadRunnerMode,
    RunManifest,
    SemanticDiffSummary,
    SerializableContract,
    SourceDataContract,
    StageGate,
    deterministic_json,
    ensure_artifact_parents,
    validate_sha256,
)
from .source_contract import governed_xodr_source
from .roundtrip import RoundtripReport, compare_roundtrip, write_report
from .validation import (
    DiffClassification,
    DiffRecord,
    GateResult,
    RoundtripConfig,
    apply_hard_gates,
    compute_overall_status,
)
from .xodr_diff import (
    ControllerInfo,
    ElevationSegment,
    GeometrySegment,
    JunctionConnection,
    JunctionInfo,
    LaneInfo,
    LaneLink,
    LaneSectionInfo,
    LaneWidth,
    ObjectInfo,
    RoadInfo,
    RoadLink,
    RoadMarkInfo,
    SignalInfo,
    SuperelevationSegment,
    XodrSnapshot,
    compute_diffs,
    parse_xodr,
)
from .export_inventory import (
    BoundingBox,
    ExportInventory,
    ExportInventoryValidation,
    FileRecord,
    LodEntry,
    MaterialRecord,
    MeshStats,
    SemanticGroupRecord,
    TileRecord,
    validate_export_inventory,
)
from .mesh_manifest import (
    LodLevelManifest,
    MaterialManifest,
    MeshBoundingBox,
    MeshManifest,
    MeshManifestValidation,
    MeshObjectRecord,
    SemanticGroupManifest,
    TextureReference,
    validate_mesh_manifest,
    validate_mesh_manifest_result,
)
from .semantic_manifest import (
    CollisionProfile,
    SemanticClassEntry,
    SemanticManifest,
    SemanticManifestValidation,
    SemanticMaterialMapping,
    validate_semantic_manifest,
    validate_semantic_manifest_result,
)
from .alignment import (
    AlignmentMetrics,
    AlignmentResult,
    AlignmentValidation,
    ControlPoint,
    ResidualSample,
    compute_control_point_fit,
    compute_heading_error,
    compute_scale_error,
    compute_translation_error,
    detect_y_inversion,
    validate_alignment_result,
    validate_alignment_result_structured,
)
from .package_manifest import (
    PackageJsonMetadata,
    PackageManifest,
    PackageManifestValidation,
    TileEntry,
    XodrAuthorityEntry,
    validate_package_manifest,
    validate_package_manifest_result,
)

__all__ = [
    "AlignmentMetrics",
    "AlignmentResult",
    "AlignmentValidation",
    "ArtifactRecord",
    "ArtifactRole",
    "AuthorityClass",
    "BoundingBox",
    "CapabilityResult",
    "CapabilityReport",
    "CollisionProfile",
    "ControlPoint",
    "DEFAULT_GATE_MATRIX",
    "DEFAULT_GATE_MATRIX_MODEL",
    "DiffClassification",
    "DiffRecord",
    "ElevationSegment",
    "ExportInventory",
    "ExportInventoryValidation",
    "ExportOptions",
    "ExportProfile",
    "FileRecord",
    "GateMatrix",
    "GateMatrixDecision",
    "GateMatrixProfile",
    "GateStatus",
    "GrpcJob",
    "GrpcResult",
    "ImportOptions",
    "ImportProfile",
    "InstallResult",
    "InstallationCapability",
    "InstallationReport",
    "LodEntry",
    "LodLevelManifest",
    "MaterialManifest",
    "MaterialRecord",
    "MeshBoundingBox",
    "MeshManifest",
    "MeshManifestValidation",
    "MeshObjectRecord",
    "MeshStats",
    "MeshXodrAlignmentSummary",
    "PackageJsonMetadata",
    "PackageManifest",
    "PackageManifestValidation",
    "PathKind",
    "PathRef",
    "ResidualSample",
    "RoadRunnerContractError",
    "RoadRunnerGateError",
    "RoadRunnerJobRequest",
    "RoadRunnerMode",
    "ProbeResult",
    "RunJobManifest",
    "RunManifest",
    "RunResult",
    "run_capability_probe",
    "run_grpc_job",
    "run_matlab_job",
    "run_process",
    "SemanticDiffSummary",
    "SemanticGroupManifest",
    "SemanticGroupRecord",
    "SemanticManifest",
    "SemanticManifestValidation",
    "SemanticMaterialMapping",
    "SerializableContract",
    "SourceDataContract",
    "StageGate",
    "TextureReference",
    "TileEntry",
    "TileRecord",
    "XodrAuthorityEntry",
    "artifact_fingerprints",
    "assert_release_allowed",
    "build_run_manifest",
    "compute_control_point_fit",
    "compute_heading_error",
    "compute_scale_error",
    "compute_translation_error",
    "deterministic_json",
    "detect_y_inversion",
    "ensure_artifact_parents",
    "evaluate_gate_matrix",
    "governed_xodr_source",
    "validate_alignment_result",
    "validate_alignment_result_structured",
    "validate_export_inventory",
    "validate_mesh_manifest",
    "validate_mesh_manifest_result",
    "validate_package_manifest",
    "validate_package_manifest_result",
    "validate_semantic_manifest",
    "validate_semantic_manifest_result",
    "validate_sha256",
]
