"""Junction road-link vs. connection-list coverage check.

Why this exists
----------------
This pipeline's `<junction>`/`<connection>` data is not generated by this
codebase -- it comes from an external OSM->XODR converter (SUMO netconvert /
CARLA's Osm2Odr). Round-3 investigation (WS-H,
reports/post_audit_hardening/WS_H_ISOLATED_LANE_JUNCTION_CONNECTION_20260904.md)
found that on the real map-of-record candidate, ~29% of roads (9,350/32,267)
have a `<road><link><predecessor|successor elementType="junction">` naming a
junction they approach, but that junction's own `<connection
incomingRoad="...">` list never cites them. Most are rescued by a correctly-
linked other end, but a handful end up genuinely, verifiably isolated
(`component_reachability_summary`'s `isolated_lane_component_count`).

This module only DETECTS the gap and classifies whether it's safely
repairable -- it does not mutate anything. A gap is repairable only when the
omitted road's approach pose geometrically matches exactly one of the
junction's existing `connectingRoad` attachment points, in both position
*and* heading:

- Position alone is not enough: unlike `ultimate_pipeline/map_fixes/
  xodr_junction_links.py`'s problem (disambiguating a road's own two ends,
  which are typically far apart), this checker must pick the correct
  connecting road *among several others converging at the same junction
  throat*, where an unrelated road can sit just as close but point in the
  wrong direction.
- Roundabout-classified junctions are explicitly excluded: their connection
  lists are wholesale-rewritten elsewhere
  (`ultimate_pipeline.topology.roundabout_reconstructor.RoundaboutReconstructor`),
  so an apparent gap there may be a stale/mid-transformation artifact rather
  than a genuine converter bug.

Reuses, rather than reimplements, this pipeline's existing geometry
primitives:
- `check_geometric_continuity._parse_geometries` / `_pose_at_s` / `_endpoint_s`
  / `_source_endpoint_for_link` / `_expected_heading_delta_rad` / `_angle_diff`
  -- the same pose-at-endpoint and expected-heading-delta math already used
  to validate *existing* road-to-road links, applied here to find a missing
  connection's best candidate instead.
- `roundabout_reconstructor._RoundaboutDetector.detect` -- the same detector
  the pipeline's own roundabout reconstruction step uses.
"""

from __future__ import annotations

import math
import os
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Optional, Union

from ultimate_pipeline.quality.check_geometric_continuity import (
    _angle_diff,
    _endpoint_s,
    _expected_heading_delta_rad,
    _parse_geometries,
    _pose_at_s,
    _road_length,
    _source_endpoint_for_link,
)
from ultimate_pipeline.topology.roundabout_reconstructor import _RoundaboutDetector

XodrInput = Union[str, os.PathLike, ET.Element]

CONFIDENT = "CONFIDENT"
AMBIGUOUS = "AMBIGUOUS"
NO_CANDIDATE = "NO_CANDIDATE"


def _load_root(xodr_path_or_root: XodrInput) -> ET.Element:
    if isinstance(xodr_path_or_root, ET.Element):
        return xodr_path_or_root
    tree = ET.parse(str(xodr_path_or_root))
    return tree.getroot()


def check_junction_connection_coverage(
    xodr_path_or_root: XodrInput,
    tolerance_m: float = 5.0,
    eps_hdg: float = 0.01,
) -> Dict[str, Any]:
    """Detect roads whose junction-typed link isn't cited as `incomingRoad`
    in that junction's own connection list, and classify each gap by whether
    a confident geometric+heading match to an existing `connectingRoad`
    exists. Read-only -- no XML mutation."""
    root = _load_root(xodr_path_or_root)

    roads_by_id: Dict[str, ET.Element] = {
        r.get("id"): r for r in root.findall("road") if r.get("id")
    }
    junctions_by_id: Dict[str, ET.Element] = {
        j.get("id"): j for j in root.findall("junction") if j.get("id")
    }

    roundabout_ids, _meta = _RoundaboutDetector.detect(root)
    roundabout_ids = set(roundabout_ids.keys())

    # junction_id -> set of incomingRoad ids already cited
    cited_incoming: Dict[str, set] = {}
    # junction_id -> set of distinct connectingRoad ids (candidates)
    connecting_candidates: Dict[str, set] = {}
    for jid, junction in junctions_by_id.items():
        cited = set()
        candidates = set()
        for conn in junction.findall("connection"):
            incoming = conn.get("incomingRoad")
            connecting = conn.get("connectingRoad")
            if incoming:
                cited.add(str(incoming))
            if connecting:
                candidates.add(str(connecting))
        cited_incoming[jid] = cited
        connecting_candidates[jid] = candidates

    geom_cache: Dict[str, Any] = {}

    def get_geoms(rid: str):
        if rid not in geom_cache:
            road = roads_by_id.get(rid)
            geom_cache[rid] = _parse_geometries(road)[0] if road is not None else []
        return geom_cache[rid]

    def pose_at_endpoint(rid: str, endpoint: str):
        geoms = get_geoms(rid)
        length = _road_length(roads_by_id[rid])
        pose, _warn = _pose_at_s(geoms, _endpoint_s(endpoint, length))
        return pose

    gaps: List[Dict[str, Any]] = []
    skipped_roundabout = 0
    confident_count = 0
    ambiguous_count = 0
    no_candidate_count = 0
    confident_contact_point_disagrees_with_start = 0

    for rid, road in roads_by_id.items():
        link_el = road.find("link")
        if link_el is None:
            continue
        for link_kind in ("predecessor", "successor"):
            el = link_el.find(link_kind)
            if el is None:
                continue
            if (el.get("elementType") or "").strip() != "junction":
                continue
            jid = (el.get("elementId") or "").strip()
            if not jid or jid not in junctions_by_id:
                continue

            if jid in roundabout_ids:
                skipped_roundabout += 1
                continue

            if rid in cited_incoming.get(jid, set()):
                continue  # already correctly cited -- no gap

            from_endpoint = _source_endpoint_for_link(link_kind)
            pose_from = pose_at_endpoint(rid, from_endpoint)

            passing: List[Dict[str, Any]] = []
            for candidate_rid in connecting_candidates.get(jid, set()):
                if candidate_rid not in roads_by_id:
                    continue
                for to_endpoint in ("start", "end"):
                    pose_to = pose_at_endpoint(candidate_rid, to_endpoint)
                    dx = pose_to.x - pose_from.x
                    dy = pose_to.y - pose_from.y
                    dxy = math.hypot(dx, dy)
                    expected_delta = _expected_heading_delta_rad(from_endpoint, to_endpoint)
                    dhdg = abs(_angle_diff(pose_to.hdg, pose_from.hdg + expected_delta))
                    if not math.isfinite(dxy) or not math.isfinite(dhdg):
                        continue
                    if dxy <= tolerance_m and dhdg <= eps_hdg:
                        passing.append(
                            {
                                "connecting_road": candidate_rid,
                                "contact_point": to_endpoint,
                                "dxy_m": dxy,
                                "dhdg_rad": dhdg,
                            }
                        )

            passing.sort(key=lambda m: (m["dxy_m"], m["dhdg_rad"]))

            gap: Dict[str, Any] = {
                "road_id": rid,
                "junction_id": jid,
                "link_kind": link_kind,
                "from_endpoint": from_endpoint,
            }

            if len(passing) == 1:
                classification = CONFIDENT
                confident_count += 1
                gap["match"] = passing[0]
                if passing[0]["contact_point"] != "start":
                    confident_contact_point_disagrees_with_start += 1
            elif len(passing) >= 2:
                classification = AMBIGUOUS
                ambiguous_count += 1
                gap["candidates"] = passing
            else:
                classification = NO_CANDIDATE
                no_candidate_count += 1

            gap["classification"] = classification
            gaps.append(gap)

    return {
        "ok": True,
        "tolerance_m": float(tolerance_m),
        "eps_hdg": float(eps_hdg),
        "total_gaps": len(gaps),
        "confident_count": confident_count,
        "ambiguous_count": ambiguous_count,
        "no_candidate_count": no_candidate_count,
        "skipped_roundabout_junction_links": skipped_roundabout,
        "confident_contact_point_disagrees_with_start": confident_contact_point_disagrees_with_start,
        "gaps": gaps,
    }
