#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Blender Runner Module (OBJ to FBX Conversion for Unreal/CARLA)

Converts OBJ files from OSM2World to FBX format for import into Unreal Engine /
CARLA, emitting a J3 manifest (Blender version, executable hash, conversion
script hash, import/export options, axes/units, FBX version, inventories,
hashes of input and output).

This is a strictly optional stage that runs last in the enrichment pipeline.

Environment Variables:
    ENABLE_BLENDER_FBX: Set to "1" to enable this stage (default: off)
    BLENDER_EXE: Path to Blender executable (default: see DEFAULT_BLENDER_EXE)
    BLENDER_TIMEOUT_SEC: Timeout in seconds (default: 600)

Usage:
    from ultimate_pipeline.enrichment.blender_runner import BlenderRunner

    runner = BlenderRunner(obj_path="/path/to/scene.obj", output_dir="/path/to/output")
    result = runner.run()
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


_BLENDER_CANDIDATE_PATHS = [
    Path(r"E:\Program Files\Blender Foundation\Blender 4.3\blender.exe"),
    Path(r"C:\Program Files\Blender Foundation\Blender 4.3\blender.exe"),
    Path(r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"),
    Path("/usr/bin/blender"),
    Path("/usr/local/bin/blender"),
    Path("/Applications/Blender.app/Contents/MacOS/Blender"),
]


def _discover_blender_exe() -> Path:
    for candidate in _BLENDER_CANDIDATE_PATHS:
        if candidate.exists():
            return candidate
    return _BLENDER_CANDIDATE_PATHS[0]


DEFAULT_BLENDER_EXE = _discover_blender_exe()


@dataclass
class BlenderResult:
    status: str
    reason: str = ""
    command_line: List[str] = field(default_factory=list)
    blender_version: str = ""
    blender_exe: str = ""
    blender_exe_hash: str = ""
    script_hash: str = ""
    input_obj: str = ""
    output_fbx: str = ""
    input_hash: str = ""
    output_hash: str = ""
    conversion_script: str = ""
    manifest: Dict[str, Any] = field(default_factory=dict)
    start_time: str = ""
    end_time: str = ""
    duration_sec: float = 0.0
    exit_code: Optional[int] = None
    exception: str = ""
    stdout_log: str = ""
    stderr_log: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status, "reason": self.reason,
            "command_line": self.command_line, "blender_version": self.blender_version,
            "blender_exe": self.blender_exe, "blender_exe_hash": self.blender_exe_hash,
            "script_hash": self.script_hash, "input_obj": self.input_obj,
            "output_fbx": self.output_fbx, "input_hash": self.input_hash,
            "output_hash": self.output_hash, "conversion_script": self.conversion_script,
            "manifest": self.manifest, "start_time": self.start_time,
            "end_time": self.end_time, "duration_sec": self.duration_sec,
            "exit_code": self.exit_code, "exception": self.exception,
            "stdout_log": self.stdout_log, "stderr_log": self.stderr_log,
        }


# Conversion script emitted to disk; imports OBJ, exports FBX, writes J3 manifest.
CONVERSION_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
# Blender OBJ->FBX conversion with J3 manifest (auto-generated by blender_runner.py)
import bpy, sys, os, json, hashlib, traceback

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()

def _s(x):
    if isinstance(x, (bytes, bytearray)):
        return x.decode("utf-8", "replace")
    return str(x)

def main():
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        print("ERROR: no args after '--'", flush=True); sys.exit(1)
    if len(argv) < 3:
        print("ERROR: need input.obj output.fbx manifest.json", flush=True); sys.exit(1)
    input_obj, output_fbx, manifest_path = argv[0], argv[1], argv[2]

    manifest = {"blender_version": bpy.app.version_string,
                "blender_build_commit_time": _s(bpy.app.build_commit_time)}
    unit = bpy.context.scene.unit_settings
    manifest["scene_unit_system"] = unit.system
    manifest["scene_unit_scale"] = unit.scale_length

    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        if hasattr(bpy.ops.wm, "obj_import"):
            bpy.ops.wm.obj_import(filepath=input_obj)
            manifest["import_operator"] = "wm.obj_import"
        else:
            bpy.ops.import_scene.obj(filepath=input_obj)
            manifest["import_operator"] = "import_scene.obj"
        manifest["import_options"] = {"filepath": input_obj}
        print("[BLENDER] OBJ import successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR importing OBJ: {e}", flush=True); traceback.print_exc(); sys.exit(1)

    mesh_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    inventory = []
    for o in mesh_objects:
        mesh = o.data
        inventory.append({
            "name": o.name, "type": o.type,
            "vertices": len(mesh.vertices), "faces": len(mesh.polygons),
            "uv_layers": len(mesh.uv_layers),
            "materials": [m.name for m in mesh.materials if m],
            "bounds": [[round(c, 6) for c in corner] for corner in o.bound_box],
        })
    manifest["objects"] = inventory
    manifest["objects_total"] = len(mesh_objects)
    manifest["materials_total"] = len(bpy.data.materials)
    manifest["images_total"] = len(bpy.data.images)
    manifest["input_obj_hash"] = sha256_file(input_obj)

    output_dir = os.path.dirname(output_fbx)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    try:
        bpy.ops.preferences.addon_enable(module="io_scene_fbx")
    except Exception as e:
        print(f"[BLENDER] WARN io_scene_fbx: {e}", flush=True)
    export_options = dict(
        filepath=output_fbx, use_selection=False, global_scale=1.0,
        apply_unit_scale=True, apply_scale_options='FBX_SCALE_NONE',
        axis_forward='-Z', axis_up='Y',
        object_types={'MESH', 'ARMATURE', 'EMPTY'},
        use_mesh_modifiers=True, mesh_smooth_type='OFF', use_mesh_edges=False,
        use_tspace=False, use_custom_props=False, add_leaf_bones=False,
        primary_bone_axis='Y', secondary_bone_axis='X', armature_nodetype='NULL',
        bake_anim=False, path_mode='AUTO', embed_textures=False, batch_mode='OFF',
    )
    try:
        bpy.ops.export_scene.fbx(**export_options)
        print("[BLENDER] FBX export successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR exporting FBX: {e}", flush=True); traceback.print_exc(); sys.exit(1)
    manifest["export_operator"] = "export_scene.fbx"
    manifest["export_options"] = {
        k: (sorted(v) if isinstance(v, (set, frozenset)) else v) for k, v in export_options.items()}

    if os.path.exists(output_fbx) and os.path.getsize(output_fbx) > 0:
        manifest["output_fbx_hash"] = sha256_file(output_fbx)
        with open(output_fbx, "rb") as fh:
            raw = fh.read(320)
        if raw.startswith(b"Kaydara FBX Binary"):
            manifest["fbx_format"] = "binary"
            manifest["fbx_signature"] = raw.split(b"\\x00")[0].decode("ascii", "replace").strip()
            ver_int = None
            for candidate in (7500, 7501, 7400, 7100, 6100):
                if candidate.to_bytes(4, "little") in raw[:320]:
                    ver_int = candidate; break
            manifest["fbx_version_int"] = ver_int
            manifest["fbx_header"] = manifest["fbx_signature"]
            manifest["fbx_version"] = f"FBX binary int={ver_int}" if ver_int else "FBX binary"
        else:
            try:
                first = raw.decode("ascii", "replace").splitlines()[0]
            except Exception:
                first = "<undecodable>"
            manifest["fbx_format"] = "ascii"; manifest["fbx_signature"] = first; manifest["fbx_version"] = first
        print(f"[BLENDER] Output FBX: {os.path.getsize(output_fbx)/(1024*1024):.2f} MB", flush=True)
    else:
        print("[BLENDER] ERROR: empty/missing FBX", flush=True); sys.exit(1)

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print("[BLENDER] CONVERSION_OK", flush=True)
    sys.exit(0)

if __name__ == "__main__":
    main()
'''


class BlenderRunner:
    def __init__(
        self,
        obj_path: str,
        output_dir: str,
        blender_exe: Optional[str] = None,
        timeout_sec: Optional[int] = None,
        name_prefix: Optional[str] = None,
    ):
        self.obj_path = Path(obj_path)
        self.output_dir = Path(output_dir)
        self.name_prefix = name_prefix or "scene"
        default_timeout = 600
        env_timeout = os.getenv("BLENDER_TIMEOUT_SEC", "").strip()
        if env_timeout.isdigit():
            default_timeout = int(env_timeout)
        self.timeout_sec = timeout_sec if timeout_sec is not None else default_timeout
        if blender_exe:
            self.blender_exe = Path(blender_exe)
        else:
            env_exe = os.getenv("BLENDER_EXE", "").strip()
            self.blender_exe = Path(env_exe) if env_exe else DEFAULT_BLENDER_EXE

    def _hash_file(self, path: Path) -> str:
        if not path.exists():
            return ""
        h = hashlib.sha256()
        try:
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            return h.hexdigest()
        except Exception:
            return ""

    def _check_blender(self) -> Tuple[bool, str]:
        if not self.blender_exe.exists():
            return False, f"Blender not found at: {self.blender_exe}"
        try:
            result = subprocess.run([str(self.blender_exe), "--version"],
                                    capture_output=True, text=True, timeout=30)
            output = result.stdout or result.stderr or ""
            for line in output.strip().split("\n"):
                if "Blender" in line:
                    return True, line.strip()
            return True, output.split("\n")[0].strip() if output else "unknown"
        except subprocess.TimeoutExpired:
            return False, "Blender version check timed out"
        except Exception as e:
            return False, f"Blender check failed: {e}"

    def _validate_obj_input(self) -> Tuple[bool, str]:
        if not self.obj_path.exists():
            return False, f"OBJ file not found: {self.obj_path}"
        if self.obj_path.stat().st_size == 0:
            return False, "OBJ file is empty"
        if self.obj_path.suffix.lower() != ".obj":
            return False, f"Unsupported format: {self.obj_path.suffix}"
        return True, ""

    def _write_conversion_script(self) -> Path:
        script_path = self.output_dir / "blender_convert.py"
        script_path.write_text(CONVERSION_SCRIPT_TEMPLATE, encoding="utf-8")
        return script_path

    def run(self) -> BlenderResult:
        result = BlenderResult(status="failed")
        result.start_time = datetime.now().isoformat()
        start_ts = time.time()
        try:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            valid, msg = self._validate_obj_input()
            if not valid:
                result.status = "skipped"
                result.reason = msg
                return self._finalize(result, start_ts)
            blender_ok, blender_ver = self._check_blender()
            result.blender_version = blender_ver
            result.blender_exe = str(self.blender_exe)
            if not blender_ok:
                result.status = "skipped"
                result.reason = f"Blender not available: {blender_ver}"
                return self._finalize(result, start_ts)

            result.input_obj = str(self.obj_path)
            result.input_hash = self._hash_file(self.obj_path)
            fbx_path = self.output_dir / f"{self.name_prefix}.fbx"
            result.output_fbx = str(fbx_path)
            manifest_path = self.output_dir / f"{self.name_prefix}.blender_manifest.json"

            script_path = self._write_conversion_script()
            result.conversion_script = str(script_path)
            result.script_hash = self._hash_file(script_path)
            result.blender_exe_hash = self._hash_file(self.blender_exe)

            cmd = [str(self.blender_exe), "--background", "--python-exit-code", "1",
                   "--python", str(script_path), "--",
                   str(self.obj_path), str(fbx_path), str(manifest_path)]
            result.command_line = cmd
            stdout_log = self.output_dir / "blender_stdout.log"
            stderr_log = self.output_dir / "blender_stderr.log"
            result.stdout_log = str(stdout_log)
            result.stderr_log = str(stderr_log)

            try:
                proc = subprocess.run(cmd, capture_output=True, text=True,
                                      timeout=self.timeout_sec, encoding="utf-8",
                                      errors="replace")
                result.exit_code = proc.returncode
                stdout_log.write_text(proc.stdout or "", encoding="utf-8", errors="replace")
                stderr_log.write_text(proc.stderr or "", encoding="utf-8", errors="replace")
                if "CONVERSION_OK" in (proc.stdout or ""):
                    if fbx_path.exists() and fbx_path.stat().st_size > 0:
                        result.output_hash = self._hash_file(fbx_path)
                        if manifest_path.exists():
                            try:
                                result.manifest = json.loads(
                                    manifest_path.read_text(encoding="utf-8"))
                            except Exception as e:
                                result.manifest = {"error": str(e)}
                        result.status = "ok"
                        result.reason = (f"Converted to FBX "
                                         f"({fbx_path.stat().st_size/(1024*1024):.2f} MB)")
                    else:
                        result.status = "failed"
                        result.reason = "Blender reported success but FBX is missing/empty"
                else:
                    result.status = "failed"
                    stderr_text = proc.stderr or ""
                    stdout_text = proc.stdout or ""
                    for line in (stderr_text + stdout_text).split("\n"):
                        if "ERROR" in line or "error" in line.lower():
                            result.reason = line.strip()
                            break
                    if not result.reason:
                        result.reason = f"Blender exit code {proc.returncode}"
            except subprocess.TimeoutExpired:
                result.status = "failed"
                result.reason = f"Blender timed out after {self.timeout_sec}s"
                result.exception = "TimeoutExpired"
        except Exception as e:
            result.status = "failed"
            result.reason = str(e)
            result.exception = f"{type(e).__name__}: {e}"
        return self._finalize(result, start_ts)

    def _finalize(self, result: BlenderResult, start_ts: float) -> BlenderResult:
        result.end_time = datetime.now().isoformat()
        result.duration_sec = round(time.time() - start_ts, 3)
        status_path = self.output_dir / "blender_status.json"
        try:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            with open(status_path, "w", encoding="utf-8") as f:
                json.dump(result.to_dict(), f, indent=2)
        except Exception as e:
            print(f"  Warning: could not write blender_status.json: {e}")
        return result


def run_blender_stage(
    obj_path: str, output_dir: str, blender_exe: Optional[str] = None,
    name_prefix: Optional[str] = None,
) -> BlenderResult:
    return BlenderRunner(obj_path=obj_path, output_dir=output_dir,
                         blender_exe=blender_exe, name_prefix=name_prefix).run()


def is_blender_enabled() -> bool:
    val = os.getenv("ENABLE_BLENDER_FBX", "").strip().lower()
    return val in ("1", "true", "yes", "on")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run Blender to convert OBJ to FBX")
    parser.add_argument("--obj", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--blender", help="Path to Blender executable")
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--name-prefix", default="scene")
    args = parser.parse_args()
    r = BlenderRunner(args.obj, args.out, args.blender, args.timeout, args.name_prefix)
    res = r.run()
    print(f"\nStatus: {res.status}")
    print(f"Reason: {res.reason}")
    print(f"Duration: {res.duration_sec:.1f}s")
    if res.output_fbx and Path(res.output_fbx).exists():
        print(f"Output: {res.output_fbx}")
    sys.exit(0 if res.status in ("ok", "skipped") else 1)
