#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Blender Runner Module (OBJ to FBX Conversion for Unreal/CARLA)

Converts OBJ files from OSM2World to FBX format for import into Unreal Engine / CARLA.
This is a strictly optional stage that runs last in the enrichment pipeline.

Environment Variables:
    ENABLE_BLENDER_FBX: Set to "1" to enable this stage (default: off)
    BLENDER_EXE: Path to Blender executable (default: see DEFAULT_BLENDER_EXE)
    BLENDER_TIMEOUT_SEC: Timeout in seconds (default: 600)

Usage:
    from ultimate_pipeline.enrichment.blender_runner import BlenderRunner

    runner = BlenderRunner(obj_path="/path/to/scene.obj", output_dir="/path/to/output")
    result = runner.run()
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# FBX-001: candidate paths searched in order; first existing wins.
# Override all of these with BLENDER_EXE env var.
_BLENDER_CANDIDATE_PATHS = [
    Path(r"E:\Program Files\Blender Foundation\Blender 4.3\blender.exe"),
    Path(r"C:\Program Files\Blender Foundation\Blender 4.3\blender.exe"),
    Path(r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"),
    Path("/usr/bin/blender"),
    Path("/usr/local/bin/blender"),
    Path("/Applications/Blender.app/Contents/MacOS/Blender"),
]


def _discover_blender_exe() -> Path:
    """Return first existing candidate or the legacy E: path for diagnostics."""
    for candidate in _BLENDER_CANDIDATE_PATHS:
        if candidate.exists():
            return candidate
    return _BLENDER_CANDIDATE_PATHS[0]


DEFAULT_BLENDER_EXE = _discover_blender_exe()


@dataclass
class BlenderResult:
    """Result of a Blender conversion run."""
    status: str  # "ok" | "skipped" | "failed"
    reason: str = ""
    command_line: List[str] = field(default_factory=list)
    blender_version: str = ""
    blender_exe: str = ""
    input_obj: str = ""
    output_fbx: str = ""
    input_hash: str = ""
    output_hash: str = ""
    conversion_script: str = ""
    start_time: str = ""
    end_time: str = ""
    duration_sec: float = 0.0
    exit_code: Optional[int] = None
    exception: str = ""
    stdout_log: str = ""
    stderr_log: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "reason": self.reason,
            "command_line": self.command_line,
            "blender_version": self.blender_version,
            "blender_exe": self.blender_exe,
            "input_obj": self.input_obj,
            "output_fbx": self.output_fbx,
            "input_hash": self.input_hash,
            "output_hash": self.output_hash,
            "conversion_script": self.conversion_script,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_sec": self.duration_sec,
            "exit_code": self.exit_code,
            "exception": self.exception,
            "stdout_log": self.stdout_log,
            "stderr_log": self.stderr_log,
        }


class BlenderRunner:
    """
    Runs Blender headlessly to convert OBJ to FBX.

    This is an optional post-processing stage for converting OSM2World OBJ output
    to FBX format for import into Unreal Engine / CARLA.

    Features:
    - Headless Blender execution with --background
    - Auto-generated conversion script
    - Full logging of stdout/stderr
    - Output validation
    """

    # Blender conversion script template
    CONVERSION_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Blender OBJ to FBX Conversion Script
Auto-generated by blender_runner.py
"""
import bpy
import sys
import os
import traceback

def main():
    # Parse command line arguments after "--"
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        print("ERROR: No arguments passed after '--'", flush=True)
        sys.exit(1)

    if len(argv) < 2:
        print("ERROR: Expected: input.obj output.fbx", flush=True)
        sys.exit(1)

    input_obj = argv[0]
    output_fbx = argv[1]

    print(f"[BLENDER] Input OBJ: {input_obj}", flush=True)
    print(f"[BLENDER] Output FBX: {output_fbx}", flush=True)

    # Clear default scene
    print("[BLENDER] Clearing default scene...", flush=True)
    bpy.ops.wm.read_factory_settings(use_empty=True)

    # Import OBJ
    print("[BLENDER] Importing OBJ...", flush=True)
    try:
        # Blender 4.0+ uses different import operator
        if hasattr(bpy.ops.wm, 'obj_import'):
            bpy.ops.wm.obj_import(filepath=input_obj)
        else:
            bpy.ops.import_scene.obj(filepath=input_obj)
        print("[BLENDER] OBJ import successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR importing OBJ: {e}", flush=True)
        traceback.print_exc()
        sys.exit(1)

    # Count imported objects
    obj_count = len([o for o in bpy.context.scene.objects if o.type == 'MESH'])
    print(f"[BLENDER] Imported {obj_count} mesh objects", flush=True)

    if obj_count == 0:
        print("[BLENDER] WARNING: No mesh objects imported!", flush=True)

    # Create output directory if needed
    output_dir = os.path.dirname(output_fbx)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # Export FBX
    print("[BLENDER] Exporting FBX...", flush=True)
    try:
        bpy.ops.preferences.addon_enable(module="io_scene_fbx")
    except Exception as e:
        print(f"[BLENDER] WARN: could not enable io_scene_fbx: {e}", flush=True)
    # Export FBX
    try:
        bpy.ops.export_scene.fbx(
            filepath=output_fbx,
            use_selection=False,
            global_scale=1.0,
            apply_unit_scale=True,
            apply_scale_options='FBX_SCALE_NONE',
            axis_forward='-Z',
            axis_up='Y',
            object_types={'MESH', 'ARMATURE', 'EMPTY'},
            use_mesh_modifiers=True,
            mesh_smooth_type='OFF',
            use_mesh_edges=False,
            use_tspace=False,
            use_custom_props=False,
            add_leaf_bones=False,
            primary_bone_axis='Y',
            secondary_bone_axis='X',
            armature_nodetype='NULL',
            bake_anim=False,
            path_mode='AUTO',
            embed_textures=False,
            batch_mode='OFF',
        )
        print("[BLENDER] FBX export successful", flush=True)
    except Exception as e:
        print(f"[BLENDER] ERROR exporting FBX: {e}", flush=True)
        traceback.print_exc()
        sys.exit(1)

    # Validate output
    if os.path.exists(output_fbx) and os.path.getsize(output_fbx) > 0:
        size_mb = os.path.getsize(output_fbx) / (1024 * 1024)
        print(f"[BLENDER] Output FBX size: {size_mb:.2f} MB", flush=True)
        print("[BLENDER] CONVERSION_OK", flush=True)
        sys.exit(0)
    else:
        print("[BLENDER] ERROR: Output FBX is empty or missing", flush=True)
        sys.exit(1)

if __name__ == "__main__":
    main()
'''

    def __init__(
        self,
        obj_path: str,
        output_dir: str,
        blender_exe: Optional[str] = None,
        timeout_sec: Optional[int] = None,
    ):
        """
        Initialize Blender runner.

        Args:
            obj_path: Path to input OBJ file
            output_dir: Directory to write outputs (FBX will be named scene.fbx)
            blender_exe: Path to Blender executable (uses env/default if None)
            timeout_sec: Timeout for Blender execution (default from env or 600)
        """
        self.obj_path = Path(obj_path)
        self.output_dir = Path(output_dir)

        # Timeout: env > arg > default 600
        default_timeout = 600
        env_timeout = os.getenv("BLENDER_TIMEOUT_SEC", "").strip()
        if env_timeout.isdigit():
            default_timeout = int(env_timeout)
        self.timeout_sec = timeout_sec if timeout_sec is not None else default_timeout

        # Blender exe: arg > env > default
        if blender_exe:
            self.blender_exe = Path(blender_exe)
        else:
            env_exe = os.getenv("BLENDER_EXE", "").strip()
            self.blender_exe = Path(env_exe) if env_exe else DEFAULT_BLENDER_EXE

    def _hash_file(self, path: Path) -> str:
        """Compute SHA-256 hash of a file."""
        if not path.exists():
            return ""
        h = hashlib.sha256()
        try:
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            return h.hexdigest()
        except Exception:
            return ""

    def _check_blender(self) -> Tuple[bool, str]:
        """
        Check if Blender is available and get version.

        Returns:
            Tuple of (available, version_string)
        """
        if not self.blender_exe.exists():
            return False, f"Blender not found at: {self.blender_exe}"

        try:
            result = subprocess.run(
                [str(self.blender_exe), "--version"],
                capture_output=True,
                text=True,
                timeout=30,
            )
            output = result.stdout or result.stderr or ""
            # Parse version from output like: Blender 4.3.0
            for line in output.strip().split("\n"):
                if "Blender" in line:
                    return True, line.strip()
            return True, output.split("\n")[0].strip() if output else "unknown"
        except subprocess.TimeoutExpired:
            return False, "Blender version check timed out"
        except Exception as e:
            return False, f"Blender check failed: {e}"

    def _validate_obj_input(self) -> Tuple[bool, str]:
        """Validate the input OBJ file."""
        if not self.obj_path.exists():
            return False, f"OBJ file not found: {self.obj_path}"

        if self.obj_path.stat().st_size == 0:
            return False, "OBJ file is empty"

        suffix = self.obj_path.suffix.lower()
        if suffix != ".obj":
            return False, f"Unsupported format: {suffix} (expected .obj)"

        return True, ""

    def _write_conversion_script(self) -> Path:
        """Write the conversion script to output directory."""
        script_path = self.output_dir / "blender_convert.py"
        script_path.write_text(self.CONVERSION_SCRIPT_TEMPLATE, encoding="utf-8")
        return script_path

    def run(self) -> BlenderResult:
        """
        Execute Blender to convert OBJ to FBX.

        Returns:
            BlenderResult with status and paths
        """
        result = BlenderResult(status="failed")
        result.start_time = datetime.now().isoformat()
        start_ts = time.time()

        try:
            # Ensure output directory exists
            self.output_dir.mkdir(parents=True, exist_ok=True)

            # Validate input
            valid, msg = self._validate_obj_input()
            if not valid:
                result.status = "skipped"
                result.reason = msg
                return self._finalize(result, start_ts)

            # Check Blender
            blender_ok, blender_ver = self._check_blender()
            result.blender_version = blender_ver
            result.blender_exe = str(self.blender_exe)

            if not blender_ok:
                result.status = "skipped"
                result.reason = f"Blender not available: {blender_ver}"
                return self._finalize(result, start_ts)

            # Paths
            result.input_obj = str(self.obj_path)
            result.input_hash = self._hash_file(self.obj_path)

            fbx_path = self.output_dir / "scene.fbx"
            result.output_fbx = str(fbx_path)

            # Write conversion script
            script_path = self._write_conversion_script()
            result.conversion_script = str(script_path)

            # Build command
            cmd = [
                str(self.blender_exe),
                "--background",
                "--python-exit-code", "1",
                "--python", str(script_path),
                "--",
                str(self.obj_path),
                str(fbx_path),
            ]
            result.command_line = cmd

            # Log paths
            stdout_log = self.output_dir / "blender_stdout.log"
            stderr_log = self.output_dir / "blender_stderr.log"
            result.stdout_log = str(stdout_log)
            result.stderr_log = str(stderr_log)

            # Run Blender
            try:
                proc = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout_sec,
                    encoding="utf-8",
                    errors="replace",
                )
                result.exit_code = proc.returncode

                # Write logs
                stdout_log.write_text(proc.stdout or "", encoding="utf-8", errors="replace")
                stderr_log.write_text(proc.stderr or "", encoding="utf-8", errors="replace")

                # Check for success marker in output
                if "CONVERSION_OK" in (proc.stdout or ""):
                    # Validate output
                    if fbx_path.exists() and fbx_path.stat().st_size > 0:
                        result.output_hash = self._hash_file(fbx_path)
                        result.status = "ok"
                        size_mb = fbx_path.stat().st_size / (1024 * 1024)
                        result.reason = f"Converted to FBX ({size_mb:.2f} MB)"
                    else:
                        result.status = "failed"
                        result.reason = "Blender reported success but FBX file is missing or empty"
                else:
                    result.status = "failed"
                    # Extract error from stderr
                    stderr_text = proc.stderr or ""
                    stdout_text = proc.stdout or ""
                    for line in (stderr_text + stdout_text).split("\n"):
                        if "ERROR" in line or "error" in line.lower():
                            result.reason = line.strip()
                            break
                    if not result.reason:
                        result.reason = f"Blender exit code {proc.returncode}"

            except subprocess.TimeoutExpired:
                result.status = "failed"
                result.reason = f"Blender timed out after {self.timeout_sec}s"
                result.exception = "TimeoutExpired"

        except Exception as e:
            result.status = "failed"
            result.reason = str(e)
            result.exception = f"{type(e).__name__}: {e}"

        return self._finalize(result, start_ts)

    def _finalize(self, result: BlenderResult, start_ts: float) -> BlenderResult:
        """Finalize result with timing and save status JSON."""
        result.end_time = datetime.now().isoformat()
        result.duration_sec = round(time.time() - start_ts, 3)

        # Write status JSON
        status_path = self.output_dir / "blender_status.json"
        try:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            with open(status_path, "w", encoding="utf-8") as f:
                json.dump(result.to_dict(), f, indent=2)
        except Exception as e:
            print(f"  Warning: could not write blender_status.json: {e}")

        return result


def run_blender_stage(
    obj_path: str,
    output_dir: str,
    blender_exe: Optional[str] = None,
) -> BlenderResult:
    """
    Convenience function to run Blender OBJ→FBX conversion as a pipeline stage.

    Args:
        obj_path: Path to input OBJ file
        output_dir: Directory for outputs
        blender_exe: Optional override for Blender executable

    Returns:
        BlenderResult with status and paths
    """
    runner = BlenderRunner(
        obj_path=obj_path,
        output_dir=output_dir,
        blender_exe=blender_exe,
    )
    return runner.run()


def is_blender_enabled() -> bool:
    """Check if Blender FBX stage is enabled via environment."""
    val = os.getenv("ENABLE_BLENDER_FBX", "").strip().lower()
    return val in ("1", "true", "yes", "on")


# ---------------------------------------------------------------------------
# CLI entry point for direct testing
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Run Blender to convert OBJ to FBX"
    )
    parser.add_argument("--obj", required=True, help="Path to input OBJ file")
    parser.add_argument("--out", required=True, help="Output directory")
    parser.add_argument("--blender", help="Path to Blender executable")
    parser.add_argument("--timeout", type=int, default=600, help="Timeout in seconds")

    args = parser.parse_args()

    runner = BlenderRunner(
        obj_path=args.obj,
        output_dir=args.out,
        blender_exe=args.blender,
        timeout_sec=args.timeout,
    )
    result = runner.run()

    print(f"\nStatus: {result.status}")
    print(f"Reason: {result.reason}")
    print(f"Duration: {result.duration_sec:.1f}s")
    if result.output_fbx and Path(result.output_fbx).exists():
        print(f"Output: {result.output_fbx}")

    sys.exit(0 if result.status in ("ok", "skipped") else 1)
