#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FBX round-trip validation (Phase J6).

The FBX produced by BlenderRunner is re-imported in a *second, clean*
headless Blender process (J6 requirement: round-trip must not reuse the
conversion session).  The round-trip inventory (objects, vertex/face/UV
counts, materials, bounds) is compared against the conversion manifest
inventory.

Fails if: any object name is lost, vertex/face/UV counts change, material
names change, or bounds deviate beyond tolerance.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Tuple

BOUNDS_TOL_M = 0.01

ROUNDTRIP_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FBX round-trip import (Phase J6)
Auto-generated by fbx_roundtrip.py
"""
import bpy
import sys
import json

def main():
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        print("ERROR: No arguments passed after '--'", flush=True)
        sys.exit(1)
    if len(argv) < 2:
        print("ERROR: Expected: input.fbx manifest.json", flush=True)
        sys.exit(1)
    input_fbx, manifest_path = argv[0], argv[1]

    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        bpy.ops.preferences.addon_enable(module="io_scene_fbx")
    except Exception as e:
        print(f"[RT] WARN addon: {e}", flush=True)
    print(f"[RT] Importing FBX: {input_fbx}", flush=True)
    try:
        bpy.ops.import_scene.fbx(
            filepath=input_fbx,
            global_scale=1.0,
            axis_forward='-Z',
            axis_up='Y',
        )
        print("[RT] FBX import successful", flush=True)
    except Exception as e:
        print(f"[RT] ERROR importing FBX: {e}", flush=True)
        sys.exit(1)

    manifest = {
        "blender_version": bpy.app.version_string,
        "import_operator": "import_scene.fbx",
        "import_options": {
            "filepath": input_fbx,
            "global_scale": 1.0,
            "axis_forward": "-Z",
            "axis_up": "Y",
        },
    }
    mesh_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    inventory = []
    for o in mesh_objects:
        mesh = o.data
        mats = [m.name for m in mesh.materials if m]
        bounds = [[round(c, 6) for c in corner] for corner in o.bound_box]
        inventory.append({
            "name": o.name,
            "type": o.type,
            "vertices": len(mesh.vertices),
            "faces": len(mesh.polygons),
            "uv_layers": len(mesh.uv_layers),
            "materials": mats,
            "bounds": bounds,
        })
    manifest["objects"] = inventory
    manifest["objects_total"] = len(mesh_objects)
    manifest["materials_total"] = len(bpy.data.materials)

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print("[RT] ROUNDTRIP_OK", flush=True)
    sys.exit(0)

if __name__ == "__main__":
    main()
'''


def compare_inventories(
    source_manifest: Dict[str, Any],
    roundtrip_manifest: Dict[str, Any],
    bounds_tol_m: float = BOUNDS_TOL_M,
) -> Dict[str, Any]:
    """Compare conversion-manifest inventory vs round-trip inventory."""
    src = {o["name"]: o for o in source_manifest.get("objects", [])}
    rt = {o["name"]: o for o in roundtrip_manifest.get("objects", [])}
    missing = sorted(set(src) - set(rt))
    extra = sorted(set(rt) - set(src))

    diffs: List[Dict[str, Any]] = []
    for name in sorted(set(src) & set(rt)):
        s, r = src[name], rt[name]
        for field in ("type", "vertices", "faces", "uv_layers"):
            if s.get(field) != r.get(field):
                diffs.append({"object": name, "field": field,
                              "source": s.get(field), "roundtrip": r.get(field)})
        if sorted(s.get("materials", [])) != sorted(r.get("materials", [])):
            diffs.append({"object": name, "field": "materials",
                          "source": s.get("materials"),
                          "roundtrip": r.get("materials")})
        if s.get("bounds") and r.get("bounds"):
            max_dev = max(abs(a - b)
                          for sa, ra in zip(s["bounds"], r["bounds"])
                          for a, b in zip(sa, ra))
            if max_dev > bounds_tol_m:
                diffs.append({"object": name, "field": "bounds",
                              "max_deviation_m": round(max_dev, 4)})

    ok = not missing and not extra and not diffs
    return {
        "objects_source": len(src),
        "objects_roundtrip": len(rt),
        "missing_objects": missing,
        "extra_objects": extra,
        "field_differences": diffs[:100],
        "verdict": "ROUNDTRIP_PASS" if ok else "ROUNDTRIP_FAIL",
    }


def run_fbx_roundtrip(
    fbx_path: Path,
    output_dir: Path,
    blender_exe: Path,
    source_manifest: Dict[str, Any],
    timeout_sec: int = 600,
) -> Tuple[bool, Dict[str, Any]]:
    """
    Run the round-trip import in a clean Blender and compare inventories.

    Returns (ok, report).
    """
    script_path = output_dir / "fbx_roundtrip.py"
    script_path.write_text(ROUNDTRIP_SCRIPT_TEMPLATE, encoding="utf-8")
    manifest_path = output_dir / "fbx_roundtrip_manifest.json"
    if manifest_path.exists():
        manifest_path.unlink()

    cmd = [
        str(blender_exe), "--background", "--python-exit-code", "1",
        "--python", str(script_path), "--",
        str(fbx_path), str(manifest_path),
    ]
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout_sec,
            encoding="utf-8", errors="replace")
    except subprocess.TimeoutExpired:
        return False, {"error": f"round-trip Blender timed out after {timeout_sec}s"}
    except Exception as e:
        return False, {"error": str(e)}

    stdout_log = output_dir / "fbx_roundtrip_stdout.log"
    stderr_log = output_dir / "fbx_roundtrip_stderr.log"
    stdout_log.write_text(proc.stdout or "", encoding="utf-8", errors="replace")
    stderr_log.write_text(proc.stderr or "", encoding="utf-8", errors="replace")

    if "ROUNDTRIP_OK" not in (proc.stdout or ""):
        return False, {
            "error": "round-trip import failed",
            "exit_code": proc.returncode,
            "stdout_tail": (proc.stdout or "")[-2000:],
            "stderr_tail": (proc.stderr or "")[-2000:],
        }

    try:
        rt_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as e:
        return False, {"error": f"cannot read round-trip manifest: {e}"}

    comparison = compare_inventories(source_manifest, rt_manifest)
    ok = comparison["verdict"] == "ROUNDTRIP_PASS"
    return ok, {
        "roundtrip_manifest": rt_manifest,
        "comparison": comparison,
    }
