import argparse
import csv
import json
import os
from pathlib import Path
import sys

from ultimate_pipeline.contracts.agent_sync import load_agent_sync

# Define constants for expected file names and paths
DETERMINISM_REPORT_JSON = "determinism_report.json"
DETERMINISM_HASHES_CSV = "determinism_hashes.csv"
DETERMINISM_THESIS_TABLE_CSV = "determinism_thesis_table.csv"
DETERMINISM_DELTA_CSV = "determinism_delta.csv"
FULL_REPORT_JSON = "full_report.json"
SUMMARY_CSV = "summary.csv"
REPRODUCIBILITY_HASH_JSON = "reproducibility_hash.json"
TILE_PAIRING_REPORT_JSON = "tile_pairing_report.json"
DOMAIN_GAP_STATUS_JSON = "domain_gap_status.json"
COORDINATE_SYSTEM_JSON = "coordinate_system.json"
XODR_LINK_INTEGRITY_JSON = "xodr_link_integrity.json"
JUNCTION_LINK_PATCH_REPORT_JSON = "junction_link_patch_report.json"

PERCEPTION_STATUS_JSON = "perception_status.json"
RIG_VERIFICATION_JSON = "rig_verification.json"
SCENE_READINESS_REPORT_JSON = "scene_readiness_report.json"
EGO_SPAWN_PNG = "ego_spawn.png"
CAMERA_FRONT_PNG = "camera_front.png"
LIDAR_BEV_PNG = "lidar_bev.png"
LIDAR_OVERLAY_PNG = "lidar_on_rgb_overlay.png"
OBJECTS_PLACED_JSON = "objects_placed.json"
OBJECTS_PLACED_PNG = "objects_placed.png"

REQUIRED_DOMAIN_GAP_METRICS = {
    "road_length_delta_m",
    "junction_count_delta",
    "intersection_iou",
}

LEGACY_PERCEPTION_PACKS = ["Manual_821", "Manual_828", "Gen_001"]
BOUNDED_SCENARIO_B_REQUIRED_DIRS = ("determinism", "structural_gap", "perception_poc")
BOUNDED_SCENARIO_B_OPTIONAL_PERCEPTION_DIRS = ("strict_evidence",)
CURRENT_SUMMARY_METRICS = {
    "geometry_rmse",
    "curvature_kl_divergence",
    "aggregated_composite",
}
CANONICAL_BBOX = {
    "lat_min": 48.74935649548228,
    "lon_min": 11.422268084715878,
    "lat_max": 48.77444431571603,
    "lon_max": 11.47882091528412,
}

_VALIDATION_ERRORS = []

def fail_validation(message, path=None):
    """Record a failure (do not exit immediately)."""
    if path:
        _VALIDATION_ERRORS.append(f"ERROR: {message} at: {path}")
    else:
        _VALIDATION_ERRORS.append(f"ERROR: {message}")


def _is_bounded_scenario_b_layout(run_root: Path) -> bool:
    return all((run_root / required).is_dir() for required in BOUNDED_SCENARIO_B_REQUIRED_DIRS)


def _contract_determinism_artifacts() -> list[str]:
    try:
        repo_root = Path(__file__).resolve().parents[2]
        contract = load_agent_sync(repo_root / "agent_sync.yaml")
        artifacts = list(getattr(contract.artifacts, "determinism", []) or [])
        normalized = [str(item).strip() for item in artifacts if str(item).strip()]
        if normalized:
            return normalized
    except Exception:
        pass
    return [
        DETERMINISM_REPORT_JSON,
        DETERMINISM_HASHES_CSV,
        DETERMINISM_THESIS_TABLE_CSV,
        DETERMINISM_DELTA_CSV,
    ]


def _validate_determinism_bundle(determinism_path: Path, *, label: str) -> None:
    if not determinism_path.is_dir():
        fail_validation(f"{label} folder not found", determinism_path)
        return

    contract_artifacts = _contract_determinism_artifacts()
    report_file = DETERMINISM_REPORT_JSON
    csv_artifacts = [name for name in contract_artifacts if name.lower().endswith(".csv")]

    report_json_path = determinism_path / report_file
    if not report_json_path.is_file():
        fail_validation(f"Missing required file in {label}", report_json_path)

    # Relax CSV checks: prefer canonical YAML artifact names, but accept any CSV
    # generated by the currently shipped determinism layout.
    found_csvs = [
        determinism_path / name for name in csv_artifacts if (determinism_path / name).is_file()
    ]
    if not found_csvs:
        found_csvs = sorted(determinism_path.glob("*.csv"))
    if not found_csvs:
        fail_validation(f"Missing required CSV artifacts in {label}", determinism_path)

    try:
        with open(report_json_path, "r", encoding="utf-8") as f:
            report_data = json.load(f)
        verdict = report_data.get("verdict") or report_data.get("report", {}).get("verdict")
        if verdict is None:
            identical = report_data.get("identical")
            if isinstance(identical, bool):
                verdict = "DETERMINISTIC" if identical else "NONDETERMINISTIC"
        if verdict not in ["DETERMINISTIC", "NATURAL_RANDOMIZATION", "NONDETERMINISTIC"]:
            fail_validation(
                f"Invalid determinism outcome in {DETERMINISM_REPORT_JSON}: "
                f"verdict={verdict!r}, identical={report_data.get('identical')!r}",
                report_json_path,
            )
        status = str(report_data.get("status", "")).strip().lower()
        if status and status not in {"pass", "ok", "computed", "success"}:
            fail_validation(
                f"{DETERMINISM_REPORT_JSON} status must be pass/ok/computed/success when present",
                report_json_path,
            )
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {DETERMINISM_REPORT_JSON}", report_json_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {DETERMINISM_REPORT_JSON}: {exc}", report_json_path)


def _rig_bool(rig_data: dict, key: str):
    if key in rig_data:
        return rig_data.get(key)
    compliance = rig_data.get("thesis_compliance")
    if isinstance(compliance, dict):
        return compliance.get(key)
    return None


def _extract_bbox_values(payload: dict) -> dict | None:
    if not isinstance(payload, dict):
        return None
    candidates = [
        payload.get("bbox"),
        payload.get("osm_bbox_wgs84"),
        payload,
    ]
    aliases = {
        "lat_min": ["lat_min", "latMin", "Lat-Min", "min_lat"],
        "lon_min": ["lon_min", "lonMin", "Lon-Min", "min_lon"],
        "lat_max": ["lat_max", "latMax", "Lat-Max", "max_lat"],
        "lon_max": ["lon_max", "lonMax", "Lon-Max", "max_lon"],
    }
    for cand in candidates:
        if not isinstance(cand, dict):
            continue
        out = {}
        ok = True
        for key, keys in aliases.items():
            val = None
            for k in keys:
                if k in cand:
                    val = cand.get(k)
                    break
            if val is None:
                ok = False
                break
            try:
                out[key] = float(val)
            except Exception:
                ok = False
                break
        if ok:
            return out
    return None


def _validate_rig_contract_schema(rig_data: dict, rig_verification_path: Path) -> bool:
    ok = True
    required = [
        "use_K_undistortion_only",
        "ignored_K_and_D",
        "ctv_inverted",
        "vtl_inverted",
    ]
    for key in required:
        if key not in rig_data:
            fail_validation(f"Missing top-level '{key}' in {RIG_VERIFICATION_JSON}", rig_verification_path)
            ok = False
    compliance = rig_data.get("thesis_compliance")
    if not isinstance(compliance, dict):
        fail_validation(f"Missing 'thesis_compliance' object in {RIG_VERIFICATION_JSON}", rig_verification_path)
        return False
    for key in required:
        if key not in compliance:
            fail_validation(f"Missing thesis_compliance '{key}' in {RIG_VERIFICATION_JSON}", rig_verification_path)
            ok = False
    return ok


def validate_agent_sync_contract():
    repo_root = Path(__file__).resolve().parents[2]
    path = repo_root / "agent_sync.yaml"
    if not path.is_file():
        fail_validation("agent_sync.yaml not found at repository root", path)
        return
    try:
        contract = load_agent_sync(path)
    except Exception as exc:
        fail_validation(f"Failed to load canonical YAML contract: {exc}", path)
        return

    bbox_actual = {
        "lat_min": float(contract.bbox.lat_min),
        "lon_min": float(contract.bbox.lon_min),
        "lat_max": float(contract.bbox.lat_max),
        "lon_max": float(contract.bbox.lon_max),
    }
    for key, expected in CANONICAL_BBOX.items():
        actual = bbox_actual.get(key)
        if actual is None or abs(float(actual) - float(expected)) > 1e-12:
            fail_validation(
                f"agent_sync.yaml bbox mismatch for {key}: expected {expected}, got {actual}",
                path,
            )

    expected_sensor_values = {
        "use_K_undistortion": True,
        "ignore_K": True,
        "ignore_D": True,
        "ctv_inverted": False,
        "vtl_inverted": True,
    }
    sensor = contract.sensor_rig
    for field, expected in expected_sensor_values.items():
        actual = getattr(sensor, field, None)
        if actual is not expected:
            fail_validation(
                f"agent_sync.yaml sensor_rig mismatch for {field}: expected {expected}, got {actual}",
                path,
            )


def validate_bbox_contract(run_root: Path, strict_mode: bool) -> None:
    bbox_path = run_root / "bbox.json"
    if not bbox_path.is_file():
        if strict_mode:
            fail_validation("Missing bbox.json in strict mode", bbox_path)
        return
    try:
        payload = json.loads(bbox_path.read_text(encoding="utf-8", errors="replace"))
    except Exception as exc:
        fail_validation(f"Failed to parse bbox.json: {exc}", bbox_path)
        return

    bbox = _extract_bbox_values(payload)
    if bbox is None:
        fail_validation("bbox.json missing canonical bbox values", bbox_path)
        return
    for key, expected in CANONICAL_BBOX.items():
        actual = bbox.get(key)
        if actual is None or abs(float(actual) - float(expected)) > 1e-12:
            fail_validation(f"bbox.json mismatch for {key}: expected {expected}, got {actual}", bbox_path)

    if strict_mode:
        has_link = isinstance(payload, dict) and isinstance(payload.get("settings_snapshot_path"), str) and bool(payload.get("settings_snapshot_path"))
        has_checksum = isinstance(payload, dict) and isinstance(payload.get("settings_snapshot_sha256"), str) and bool(payload.get("settings_snapshot_sha256"))
        if not (has_link or has_checksum):
            fail_validation(
                "bbox.json must include settings snapshot linkage/checksum in strict mode",
                bbox_path,
            )

def validate_determinism_audit(run_root: Path):
    """
    Validates the determinism audit folder structure and content.
    """
    print(f"Validating determinism audit in: {run_root / 'determinism_audit'}")
    _validate_determinism_bundle(run_root / "determinism_audit", label="determinism audit")
    print("Determinism audit validation successful.")


def _validate_domain_gap_bundle(domain_gap_path: Path, strict_mode: bool, *, require_coordinate_system: bool) -> None:
    expected_files = [
        FULL_REPORT_JSON,
        SUMMARY_CSV,
        REPRODUCIBILITY_HASH_JSON,
        TILE_PAIRING_REPORT_JSON,
        DOMAIN_GAP_STATUS_JSON,
    ]
    if require_coordinate_system:
        expected_files.append(COORDINATE_SYSTEM_JSON)
    for file_name in expected_files:
        file_path = domain_gap_path / file_name
        if not file_path.is_file():
            fail_validation("Missing required file in comparison domain_gap", file_path)

    pairing_report_path = domain_gap_path / TILE_PAIRING_REPORT_JSON
    try:
        with open(pairing_report_path, "r", encoding="utf-8") as f:
            pairing_data = json.load(f)
        if not isinstance(pairing_data, dict):
            fail_validation(f"{TILE_PAIRING_REPORT_JSON} root must be an object", pairing_report_path)
        else:
            has_legacy_schema = "pairing_method" in pairing_data
            has_current_schema = "algorithm" in pairing_data and "matches" in pairing_data
            if has_legacy_schema:
                pairing_method = pairing_data.get("pairing_method")
                one_to_one_ok = pairing_data.get("one_to_one", {}).get("ok")
                dup_manual = pairing_data.get("one_to_one", {}).get("duplicate_manual")
                dup_auto = pairing_data.get("one_to_one", {}).get("duplicate_auto")
                if pairing_method not in ["hungarian", "greedy"]:
                    fail_validation(f"Invalid 'pairing_method' in {TILE_PAIRING_REPORT_JSON}: {pairing_method}", pairing_report_path)
                if one_to_one_ok is not True:
                    fail_validation(
                        f"Expected 'one_to_one.ok' to be True in {TILE_PAIRING_REPORT_JSON}, but got {one_to_one_ok} "
                        f"(duplicate_manual={dup_manual}, duplicate_auto={dup_auto})",
                        pairing_report_path,
                    )
                if "num_pairs" not in pairing_data:
                    fail_validation(f"Missing 'num_pairs' in {TILE_PAIRING_REPORT_JSON}", pairing_report_path)
                if "pairs" not in pairing_data or not isinstance(pairing_data.get("pairs"), list):
                    fail_validation(f"Missing 'pairs' list in {TILE_PAIRING_REPORT_JSON}", pairing_report_path)
            elif has_current_schema:
                matches = pairing_data.get("matches")
                summary = pairing_data.get("summary")
                if not isinstance(matches, dict):
                    fail_validation(f"{TILE_PAIRING_REPORT_JSON} current schema requires dict 'matches'", pairing_report_path)
                if not isinstance(summary, dict):
                    fail_validation(f"{TILE_PAIRING_REPORT_JSON} current schema requires object 'summary'", pairing_report_path)
                if isinstance(matches, dict) and not matches:
                    fail_validation(f"{TILE_PAIRING_REPORT_JSON} current schema has empty matches", pairing_report_path)
            else:
                fail_validation(
                    f"{TILE_PAIRING_REPORT_JSON} schema unsupported (expected legacy pairing_method or current algorithm/matches)",
                    pairing_report_path,
                )
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {TILE_PAIRING_REPORT_JSON}", pairing_report_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {TILE_PAIRING_REPORT_JSON}: {exc}", pairing_report_path)

    full_report_path = domain_gap_path / FULL_REPORT_JSON
    try:
        with open(full_report_path, "r", encoding="utf-8") as f:
            full_report = json.load(f)
        if not isinstance(full_report, dict):
            fail_validation("full_report.json must be an object", full_report_path)
        else:
            domain_gap = full_report.get("domain_gap")
            structural_gap = full_report.get("structural_domain_gap")
            if isinstance(domain_gap, dict):
                for key in sorted(REQUIRED_DOMAIN_GAP_METRICS):
                    if key not in domain_gap:
                        fail_validation(f"full_report.json domain_gap missing metric '{key}'", full_report_path)
                    else:
                        try:
                            float(domain_gap.get(key))
                        except Exception:
                            fail_validation(f"full_report.json domain_gap metric '{key}' must be numeric", full_report_path)
            elif isinstance(structural_gap, dict):
                for key in ("geometry", "intersection", "curvature"):
                    if key not in structural_gap:
                        fail_validation(f"full_report.json structural_domain_gap missing '{key}'", full_report_path)
            else:
                fail_validation(
                    "full_report.json missing supported gap object (domain_gap or structural_domain_gap)",
                    full_report_path,
                )
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {FULL_REPORT_JSON}", full_report_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {FULL_REPORT_JSON}: {exc}", full_report_path)

    summary_path = domain_gap_path / SUMMARY_CSV
    try:
        with open(summary_path, "r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
            cols = [c or "" for c in (reader.fieldnames or [])]
        metric_col = "metric" if "metric" in cols else (cols[0] if cols else "")
        found_metrics = set()
        for row in rows:
            if not isinstance(row, dict):
                continue
            metric_name = str(row.get(metric_col, "")).strip() if metric_col else ""
            if metric_name:
                found_metrics.add(metric_name)
        supports_legacy = REQUIRED_DOMAIN_GAP_METRICS.issubset(found_metrics)
        supports_current = bool(CURRENT_SUMMARY_METRICS.intersection(found_metrics))
        if not (supports_legacy or supports_current):
            fail_validation(
                f"summary.csv missing supported metric set (legacy={sorted(REQUIRED_DOMAIN_GAP_METRICS)}, "
                f"current_any={sorted(CURRENT_SUMMARY_METRICS)})",
                summary_path,
            )
        if strict_mode and len(found_metrics) < 5:
            fail_validation("summary.csv appears smoke-only (<5 metrics rows) in strict mode", summary_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {SUMMARY_CSV}: {exc}", summary_path)

    status_path = domain_gap_path / DOMAIN_GAP_STATUS_JSON
    try:
        with open(status_path, "r", encoding="utf-8") as f:
            status_data = json.load(f)
        if not isinstance(status_data, dict):
            fail_validation(f"{DOMAIN_GAP_STATUS_JSON} root must be an object", status_path)
        else:
            if "success" in status_data:
                if bool(status_data.get("success")) is not True:
                    fail_validation(f"{DOMAIN_GAP_STATUS_JSON} indicates failure", status_path)
                if strict_mode and str(status_data.get("status", "")).lower() in {"fail", "failed"}:
                    fail_validation(f"{DOMAIN_GAP_STATUS_JSON} status must not be failed in strict mode", status_path)
            else:
                status_token = str(status_data.get("status", "")).strip().lower()
                if status_token and status_token in {"failed", "fail", "error"}:
                    fail_validation(f"{DOMAIN_GAP_STATUS_JSON} indicates failure", status_path)
                if "metrics" not in status_data and "composite_gap" not in status_data:
                    fail_validation(
                        f"{DOMAIN_GAP_STATUS_JSON} missing supported status keys (success or metrics/composite_gap)",
                        status_path,
                    )
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {DOMAIN_GAP_STATUS_JSON}", status_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {DOMAIN_GAP_STATUS_JSON}: {exc}", status_path)

    coordinate_path = domain_gap_path / COORDINATE_SYSTEM_JSON
    if coordinate_path.is_file():
        try:
            with open(coordinate_path, "r", encoding="utf-8") as f:
                coordinate_data = json.load(f)
            if "units" not in coordinate_data:
                fail_validation(f"Missing 'units' in {COORDINATE_SYSTEM_JSON}", coordinate_path)
            if "osm_bbox_wgs84" not in coordinate_data:
                fail_validation(f"Missing 'osm_bbox_wgs84' in {COORDINATE_SYSTEM_JSON}", coordinate_path)
        except json.JSONDecodeError:
            fail_validation(f"Invalid JSON in {COORDINATE_SYSTEM_JSON}", coordinate_path)
        except Exception as exc:
            fail_validation(f"Failed to validate {COORDINATE_SYSTEM_JSON}: {exc}", coordinate_path)
    elif require_coordinate_system:
        fail_validation("Missing required coordinate_system.json in legacy domain gap layout", coordinate_path)


def validate_comparison_folders(run_root: Path, strict_mode: bool):
    """
    Validates comparison folders in legacy and split layouts.
    """
    thesis_final_path = run_root / "thesis_final"
    if thesis_final_path.is_dir():
        comparison_runs = [d for d in thesis_final_path.iterdir() if d.is_dir()]
        if not comparison_runs:
            fail_validation("No comparison run folders found under thesis_final", thesis_final_path)
            return

        for comp_run_path in comparison_runs:
            print(f"Validating comparison run: {comp_run_path}")
            domain_gap_path = comp_run_path / "domain_gap"
            if not domain_gap_path.is_dir():
                fail_validation("Missing 'domain_gap' folder in comparison run", domain_gap_path)
                continue
            _validate_domain_gap_bundle(
                domain_gap_path, strict_mode, require_coordinate_system=True
            )
        print("Comparison folders validation successful.")
        return

    split_candidates = [
        run_root / "thesis_results" / "structural_gap_v1",
        run_root / "structural_gap_v1",
    ]
    split_root = next((p for p in split_candidates if p.is_dir()), None)
    if split_root is None:
        fail_validation(
            "No supported comparison layout found (expected thesis_final or thesis_results/structural_gap_v1)",
            run_root,
        )
        return

    comparison_runs = [d for d in split_root.iterdir() if d.is_dir()]
    if not comparison_runs:
        fail_validation("No comparison run folders found under structural_gap_v1", split_root)
        return

    for comp_run_path in comparison_runs:
        print(f"Validating comparison run: {comp_run_path}")
        domain_gap_path = comp_run_path / "domain_gap"
        if domain_gap_path.is_dir():
            _validate_domain_gap_bundle(
                domain_gap_path, strict_mode, require_coordinate_system=False
            )
        else:
            # Current structural-gap layout stores required files at run-root.
            _validate_domain_gap_bundle(
                comp_run_path, strict_mode, require_coordinate_system=False
            )
    print("Comparison folders validation successful.")


def _validate_perception_pack(
    pack_path: Path,
    pack_name: str,
    strict_mode: bool,
    *,
    require_scene_readiness: bool = True,
) -> None:
    if not pack_path.is_dir():
        fail_validation(f"Perception evidence pack '{pack_name}' not found", pack_path)
        return

    scene_readiness_path = pack_path / SCENE_READINESS_REPORT_JSON
    if not scene_readiness_path.is_file():
        if require_scene_readiness:
            fail_validation(
                f"Missing required file in perception evidence pack '{pack_name}'",
                scene_readiness_path,
            )
    else:
        try:
            with open(scene_readiness_path, "r", encoding="utf-8") as f:
                scene_readiness = json.load(f)
            if not isinstance(scene_readiness, dict):
                fail_validation(
                    f"Invalid JSON object in {SCENE_READINESS_REPORT_JSON}",
                    scene_readiness_path,
                )
            else:
                required_scene_keys = [
                    "timestamp",
                    "thesis_rig_attached",
                    "enrichments_file_found",
                    "missing_required_types",
                    "qa_bundle_written",
                    "safe_to_start_recording",
                ]
                for key in required_scene_keys:
                    if key not in scene_readiness:
                        fail_validation(
                            f"{SCENE_READINESS_REPORT_JSON} missing key: {key}",
                            scene_readiness_path,
                        )
                if not isinstance(scene_readiness.get("timestamp"), str):
                    fail_validation(
                        f"{SCENE_READINESS_REPORT_JSON} timestamp must be a string",
                        scene_readiness_path,
                    )
                for bool_key in (
                    "thesis_rig_attached",
                    "enrichments_file_found",
                    "qa_bundle_written",
                    "safe_to_start_recording",
                ):
                    if bool_key in scene_readiness and not isinstance(
                        scene_readiness.get(bool_key), bool
                    ):
                        fail_validation(
                            f"{SCENE_READINESS_REPORT_JSON} field '{bool_key}' must be boolean",
                            scene_readiness_path,
                        )

                missing_required_types = scene_readiness.get("missing_required_types")
                if not isinstance(missing_required_types, list):
                    fail_validation(
                        f"{SCENE_READINESS_REPORT_JSON} missing_required_types must be a list",
                        scene_readiness_path,
                    )
                elif len(missing_required_types) > 0:
                    fail_validation(
                        f"{SCENE_READINESS_REPORT_JSON} missing_required_types must be empty",
                        scene_readiness_path,
                    )

                if scene_readiness.get("safe_to_start_recording") is not True:
                    fail_validation(
                        f"{SCENE_READINESS_REPORT_JSON} must set safe_to_start_recording=true",
                        scene_readiness_path,
                    )
        except json.JSONDecodeError:
            fail_validation(f"Invalid JSON in {SCENE_READINESS_REPORT_JSON}", scene_readiness_path)
        except Exception as exc:
            fail_validation(
                f"Failed to validate {SCENE_READINESS_REPORT_JSON}: {exc}",
                scene_readiness_path,
            )

    expected_files = [
        PERCEPTION_STATUS_JSON,
        RIG_VERIFICATION_JSON,
        EGO_SPAWN_PNG,
        CAMERA_FRONT_PNG,
        LIDAR_BEV_PNG,
    ]
    for file_name in expected_files:
        file_path = pack_path / file_name
        if not file_path.is_file():
            fail_validation(f"Missing required file in perception evidence pack '{pack_name}'", file_path)

    strict_requested_for_pack = bool(strict_mode)
    require_overlay = bool(strict_mode)
    require_objects = bool(strict_mode)
    require_evidence_pack = bool(strict_mode)
    perception_status_path = pack_path / PERCEPTION_STATUS_JSON
    if perception_status_path.is_file():
        try:
            with open(perception_status_path, "r", encoding="utf-8") as f:
                ps = json.load(f)
            required = ps.get("required_artifacts", {}) if isinstance(ps, dict) else {}
            if isinstance(required, dict):
                require_overlay = bool(require_overlay or required.get("require_overlay"))
                require_objects = bool(require_objects or required.get("require_objects"))
                require_evidence_pack = bool(require_evidence_pack or required.get("require_evidence_pack"))
                strict_requested_for_pack = bool(
                    strict_requested_for_pack
                    or require_overlay
                    or require_objects
                    or require_evidence_pack
                )
            if strict_requested_for_pack and not isinstance(required, dict):
                fail_validation("perception_status.json missing required_artifacts block in strict mode", perception_status_path)
        except Exception:
            pass

    if require_overlay:
        strict_path = pack_path / LIDAR_OVERLAY_PNG
        if not strict_path.is_file():
            fail_validation(f"Missing strict perception artifact '{LIDAR_OVERLAY_PNG}'", strict_path)
    if require_objects:
        for strict_file in (OBJECTS_PLACED_JSON, OBJECTS_PLACED_PNG):
            strict_path = pack_path / strict_file
            if not strict_path.is_file():
                fail_validation(f"Missing strict perception artifact '{strict_file}'", strict_path)

    rig_verification_path = pack_path / RIG_VERIFICATION_JSON
    try:
        with open(rig_verification_path, "r", encoding="utf-8") as f:
            rig_data = json.load(f)
        if not _validate_rig_contract_schema(rig_data, rig_verification_path):
            return
        use_k_undist = _rig_bool(rig_data, "use_K_undistortion_only")
        ignored_kd = _rig_bool(rig_data, "ignored_K_and_D")
        ctv_inverted = _rig_bool(rig_data, "ctv_inverted")
        vtl_inverted = _rig_bool(rig_data, "vtl_inverted")
        compliance = rig_data.get("thesis_compliance", {})
        if isinstance(compliance, dict):
            if (
                compliance.get("use_K_undistortion_only") != use_k_undist
                or compliance.get("ignored_K_and_D") != ignored_kd
                or compliance.get("ctv_inverted") != ctv_inverted
                or compliance.get("vtl_inverted") != vtl_inverted
            ):
                fail_validation(
                    "Top-level rig verification values must match thesis_compliance block",
                    rig_verification_path,
                )

        if use_k_undist is not True:
            fail_validation(
                f"Expected 'use_K_undistortion_only' to be True in {RIG_VERIFICATION_JSON}, but got {use_k_undist}",
                rig_verification_path,
            )
        if ignored_kd is not True:
            fail_validation(
                f"Expected 'ignored_K_and_D' to be True in {RIG_VERIFICATION_JSON}, but got {ignored_kd}",
                rig_verification_path,
            )
        if ctv_inverted is not False:
            fail_validation(f"Expected 'ctv_inverted' to be False in {RIG_VERIFICATION_JSON}, but got {ctv_inverted}", rig_verification_path)
        if vtl_inverted is not True:
            fail_validation(f"Expected 'vtl_inverted' to be True in {RIG_VERIFICATION_JSON}, but got {vtl_inverted}", rig_verification_path)
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {RIG_VERIFICATION_JSON}", rig_verification_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {RIG_VERIFICATION_JSON}: {exc}", rig_verification_path)

    try:
        with open(perception_status_path, "r", encoding="utf-8") as f:
            ps = json.load(f)
        env = ps.get("environment", {}) if isinstance(ps, dict) else {}
        if not isinstance(env, dict):
            fail_validation("perception_status.json missing 'environment' object", perception_status_path)
        else:
            for key in ("weather", "traffic_manager_seed", "ego_spawn_transform"):
                if key not in env:
                    fail_validation(f"perception_status.json environment missing key: {key}", perception_status_path)
            if strict_requested_for_pack:
                required_artifacts = ps.get("required_artifacts")
                produced_artifacts = ps.get("produced_artifacts")
                if not isinstance(required_artifacts, dict):
                    fail_validation("perception_status.json required_artifacts missing in strict mode", perception_status_path)
                if not isinstance(produced_artifacts, dict):
                    fail_validation("perception_status.json produced_artifacts missing in strict mode", perception_status_path)
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {PERCEPTION_STATUS_JSON}", perception_status_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {PERCEPTION_STATUS_JSON}: {exc}", perception_status_path)


def validate_perception_evidence_packs(run_root: Path, strict_mode: bool):
    """
    Validates legacy perception evidence packs for Manual_821, Manual_828, Gen_001.
    """
    print(f"Validating perception evidence packs in: {run_root}")
    search_roots = [
        run_root,
        run_root / "_perception_runs",
        run_root / "thesis_runs" / "_perception_runs",
    ]
    for pack_name in LEGACY_PERCEPTION_PACKS:
        pack_path = None
        for base in search_roots:
            candidate = base / pack_name
            if candidate.is_dir():
                pack_path = candidate
                break
        if pack_path is None:
            pack_path = run_root / pack_name
        _validate_perception_pack(pack_path, pack_name, strict_mode)
    print("Perception evidence packs validation successful.")


def validate_xodr_link_integrity(run_root: Path, *, required: bool = True):
    """Validate junction-link integrity gate report."""
    report_path = run_root / XODR_LINK_INTEGRITY_JSON
    if not report_path.is_file():
        if required:
            fail_validation("Missing required xodr link integrity report", report_path)
        else:
            print(f"Skipping optional xodr link integrity check (not found): {report_path}")
        return

    patch_report_path = run_root / JUNCTION_LINK_PATCH_REPORT_JSON
    if not patch_report_path.is_file():
        fail_validation("Missing required junction link patch report", patch_report_path)

    try:
        with open(report_path, "r", encoding="utf-8") as f:
            report_data = json.load(f)
        required_keys = [
            "roads_total",
            "junctions_total",
            "added_junction_links",
            "missing_road_to_junction_links_before",
            "missing_road_to_junction_links_after",
            "remaining_unlinked_nonjunction_roads",
            "suspicious_matches",
            "notes",
            "output_xodr_path",
            "input_xodr_sha256",
            "output_xodr_sha256",
        ]
        for key in required_keys:
            if key not in report_data:
                fail_validation(f"Missing '{key}' in {XODR_LINK_INTEGRITY_JSON}", report_path)

        remaining = report_data.get("missing_road_to_junction_links_after")
        if remaining != 0:
            fail_validation(
                f"Expected 'missing_road_to_junction_links_after' to be 0 in {XODR_LINK_INTEGRITY_JSON}, but got {remaining}",
                report_path,
            )
    except json.JSONDecodeError:
        fail_validation(f"Invalid JSON in {XODR_LINK_INTEGRITY_JSON}", report_path)
    except Exception as exc:
        fail_validation(f"Failed to validate {XODR_LINK_INTEGRITY_JSON}: {exc}", report_path)


def validate_bounded_scenario_b_evidence(run_root: Path, strict_mode: bool) -> None:
    print("Detected bounded Scenario B evidence layout.")

    determinism_dir = run_root / "determinism"
    print(f"Validating bounded Scenario B determinism bundle in: {determinism_dir}")
    _validate_determinism_bundle(determinism_dir, label="determinism")

    structural_gap_dir = run_root / "structural_gap"
    if not structural_gap_dir.is_dir():
        fail_validation("Bounded Scenario B structural_gap folder not found", structural_gap_dir)
    else:
        print(f"Validating bounded Scenario B structural gap bundle in: {structural_gap_dir}")
        _validate_domain_gap_bundle(structural_gap_dir, strict_mode, require_coordinate_system=False)

    perception_poc = run_root / "perception_poc"
    print(f"Validating bounded Scenario B perception pack in: {perception_poc}")
    _validate_perception_pack(
        perception_poc,
        "perception_poc",
        strict_mode,
        require_scene_readiness=False,
    )

    for optional_pack in BOUNDED_SCENARIO_B_OPTIONAL_PERCEPTION_DIRS:
        optional_path = run_root / optional_pack
        if optional_path.is_dir():
            print(f"Validating optional bounded Scenario B perception pack in: {optional_path}")
            _validate_perception_pack(optional_path, optional_pack, strict_mode)

    validate_xodr_link_integrity(run_root, required=False)

def validate_optional_generalization_and_repro(run_root: Path, strict_mode: bool):
    """Validate optional generalization/repro artifacts when present."""

    gen_csv = run_root / "generalization_results.csv"
    gen_json = run_root / "generalization_results.json"
    gen_curve = run_root / "gen_many_curve.csv"
    gen_ci = run_root / "generalization_bootstrap_ci.json"
    real_u_report = run_root / "real_u_eval_report.json"
    any_gen = any(p.is_file() for p in (gen_csv, gen_json, gen_curve, gen_ci))
    if any_gen:
        for req in (gen_csv, gen_json, gen_curve, gen_ci, real_u_report):
            if not req.is_file():
                fail_validation("Missing generalization artifact", req)

        try:
            with open(gen_csv, "r", encoding="utf-8", newline="") as f:
                reader = csv.DictReader(f)
                cols = set(reader.fieldnames or [])
            new_required = {
                "condition",
                "K",
                "train_dataset_count",
                "sim_mIoU",
                "sim_pixel_accuracy",
                "real_u_entropy_mean",
                "real_u_confidence_mean",
                "real_u_ece",
                "checkpoint",
                "train_dataset_roots",
            }
            legacy_required = {
                "K",
                "test_target",
                "mean_entropy",
                "std_entropy",
                "p10_entropy",
                "p90_entropy",
                "ece",
                "delta_vs_manual_baseline_mean_entropy",
                "delta_vs_manual_baseline_ece",
            }
            if not (new_required.issubset(cols) or legacy_required.issubset(cols)):
                fail_validation("generalization_results.csv does not match supported schema", gen_csv)
        except Exception as exc:
            fail_validation(f"Failed to validate generalization_results.csv: {exc}", gen_csv)

        try:
            gj = json.loads(gen_json.read_text(encoding="utf-8", errors="replace"))
            if not isinstance(gj, dict):
                fail_validation("generalization_results.json must be an object", gen_json)
            else:
                if gj.get("placeholder") is True:
                    fail_validation("generalization_results.json is marked as placeholder", gen_json)
                rows = gj.get("rows")
                if not isinstance(rows, list) or not rows:
                    fail_validation("generalization_results.json missing non-empty rows", gen_json)
                elif any(isinstance(r, dict) and "test_target" in r for r in rows):
                    fail_validation("generalization_results.json appears to use placeholder/legacy rows", gen_json)
                conditioned_top = gj.get("real_u_conditioned_on_k")
                row_conditioned = [
                    r.get("real_u_conditioned_on_k")
                    for r in rows
                    if isinstance(r, dict) and "real_u_conditioned_on_k" in r
                ]
                if strict_mode and not isinstance(conditioned_top, bool):
                    fail_validation("generalization_results.json missing boolean real_u_conditioned_on_k in strict mode", gen_json)
                if strict_mode and not row_conditioned:
                    fail_validation("generalization_results.json rows missing real_u_conditioned_on_k in strict mode", gen_json)
        except Exception as exc:
            fail_validation(f"Failed to validate generalization_results.json: {exc}", gen_json)

        try:
            with open(gen_curve, "r", encoding="utf-8", newline="") as f:
                reader = csv.DictReader(f)
                cols = set(reader.fieldnames or [])
            if not {"K"}.issubset(cols):
                fail_validation("gen_many_curve.csv missing K column", gen_curve)
        except Exception as exc:
            fail_validation(f"Failed to validate gen_many_curve.csv: {exc}", gen_curve)

        try:
            ci_obj = json.loads(gen_ci.read_text(encoding="utf-8", errors="replace"))
            if not isinstance(ci_obj, dict):
                fail_validation("generalization_bootstrap_ci.json must be an object", gen_ci)
            elif not isinstance(ci_obj.get("rows"), list):
                fail_validation("generalization_bootstrap_ci.json missing rows list", gen_ci)
        except Exception as exc:
            fail_validation(f"Failed to validate generalization_bootstrap_ci.json: {exc}", gen_ci)

        try:
            data = json.loads(real_u_report.read_text(encoding="utf-8", errors="replace"))
            real = data.get("real", {}) if isinstance(data, dict) else {}
            if not isinstance(real, dict):
                fail_validation("Invalid Real_U report schema: missing real block", real_u_report)
            else:
                required = (
                    "entropy_mean",
                    "entropy_std",
                    "entropy_p10",
                    "entropy_p90",
                    "confidence_mean",
                    "confidence_std",
                    "confidence_p10",
                    "confidence_p90",
                    "ece",
                    "entropy_values",
                    "confidence_values",
                    "ece_values",
                )
                for key in required:
                    if key not in real:
                        fail_validation(f"Real_U report missing key {key}", real_u_report)
                if not isinstance(real.get("entropy_values"), list):
                    fail_validation("Real_U report entropy_values must be a list", real_u_report)
                if not isinstance(real.get("confidence_values"), list):
                    fail_validation("Real_U report confidence_values must be a list", real_u_report)
                if not isinstance(real.get("ece_values"), list):
                    fail_validation("Real_U report ece_values must be a list", real_u_report)
                conditioned_real = data.get("real_u_conditioned_on_k") if isinstance(data, dict) else None
                if strict_mode and not isinstance(conditioned_real, bool):
                    fail_validation("real_u_eval_report.json missing boolean real_u_conditioned_on_k in strict mode", real_u_report)
                try:
                    gj = json.loads(gen_json.read_text(encoding="utf-8", errors="replace"))
                    conditioned_top = gj.get("real_u_conditioned_on_k") if isinstance(gj, dict) else None
                except Exception:
                    conditioned_top = None
                if isinstance(conditioned_top, bool) and isinstance(conditioned_real, bool) and conditioned_real != conditioned_top:
                    fail_validation(
                        "Mismatch for real_u_conditioned_on_k between generalization_results.json and real_u_eval_report.json",
                        real_u_report,
                    )
        except Exception as exc:
            fail_validation(f"Failed to validate Real_U report: {exc}", real_u_report)

    env_snapshot = run_root / "environment_snapshot.json"
    if env_snapshot.is_file():
        try:
            env = json.loads(env_snapshot.read_text(encoding="utf-8", errors="replace"))
            for key in ("python_version", "platform", "pip_freeze_sha256"):
                if key not in env:
                    fail_validation(f"environment_snapshot.json missing key: {key}", env_snapshot)
        except Exception as exc:
            fail_validation(f"Failed to validate environment_snapshot.json: {exc}", env_snapshot)

    # If determinism_report.json exists, determinism_delta.csv must exist beside it.
    for rep in run_root.rglob("determinism_report.json"):
        delta = rep.parent / "determinism_delta.csv"
        if not delta.is_file():
            fail_validation("determinism_delta.csv required when determinism_report.json exists", delta)

    # Also enforce root-level determinism delta when root-level report exists.
    root_det_report = run_root / "determinism_report.json"
    if root_det_report.is_file():
        root_delta = run_root / "determinism_delta.csv"
        if not root_delta.is_file():
            fail_validation("Missing determinism_delta.csv", root_delta)

    # Require settings_fingerprint in pipeline report bundle (when report exists).
    report_candidates = [
        run_root / "logs" / "pipeline_report.json",
        run_root / "logs" / "validation_report_full.json",
    ]
    report_found = False
    found_fingerprint = False
    for report_path in report_candidates:
        if not report_path.is_file():
            continue
        report_found = True
        try:
            data = json.loads(report_path.read_text(encoding="utf-8", errors="replace"))
            diagnostics = data.get("diagnostics", {}) if isinstance(data, dict) else {}
            details = diagnostics.get("details", {}) if isinstance(diagnostics, dict) else {}
            fp_obj = details.get("settings_fingerprint", {}) if isinstance(details, dict) else {}
            fp = fp_obj.get("sha256") if isinstance(fp_obj, dict) else None
            if isinstance(fp, str) and fp:
                found_fingerprint = True
                break
        except Exception:
            continue
    if report_found and not found_fingerprint:
        fail_validation("Missing settings_fingerprint in pipeline report bundle")

    # Root-level pipeline_report.json support (legacy layouts)
    root_report = run_root / "pipeline_report.json"
    if root_report.is_file():
        try:
            data = json.loads(root_report.read_text(encoding="utf-8", errors="replace"))
            has_fp = False
            if isinstance(data, dict):
                if "settings_fingerprint" in data:
                    has_fp = True
                diagnostics = data.get("diagnostics", {}) if isinstance(data.get("diagnostics"), dict) else {}
                details = diagnostics.get("details", {}) if isinstance(diagnostics, dict) else {}
                if isinstance(details, dict) and "settings_fingerprint" in details:
                    has_fp = True
            if not has_fp:
                fail_validation("Missing settings_fingerprint in pipeline_report.json", root_report)
        except Exception as exc:
            fail_validation(f"Failed to validate pipeline_report.json: {exc}", root_report)

    # OSM archive requirement when run summary declares an OSM input
    run_summary = run_root / "run_summary.json"
    if run_summary.is_file():
        try:
            summary = json.loads(run_summary.read_text(encoding="utf-8", errors="replace"))
            osm_file = ""
            if isinstance(summary, dict):
                inputs = summary.get("inputs", {})
                if isinstance(inputs, dict):
                    osm_file = str(inputs.get("osm_file") or "")
            if osm_file:
                archive = run_root / "osm_archive.json"
                if not archive.is_file():
                    fail_validation("Missing osm_archive.json while OSM_FILE is declared", archive)
                else:
                    arc = json.loads(archive.read_text(encoding="utf-8", errors="replace"))
                    md5 = arc.get("osm_md5") if isinstance(arc, dict) else None
                    if not isinstance(md5, str) or not md5:
                        fail_validation("osm_archive.json missing osm_md5", archive)
                    bbox = _extract_bbox_values(arc)
                    if bbox is None:
                        inputs = summary.get("inputs", {}) if isinstance(summary, dict) else {}
                        bbox = _extract_bbox_values(inputs)
                    if bbox is None:
                        fail_validation("Missing bbox in osm_archive.json or run_summary inputs", archive)
                    else:
                        for k, v in CANONICAL_BBOX.items():
                            if abs(float(bbox.get(k, 0.0)) - float(v)) > 1e-12:
                                fail_validation(f"BBox mismatch for {k}: expected {v}, got {bbox.get(k)}", archive)
        except Exception as exc:
            fail_validation(f"Failed to validate OSM archive contract: {exc}", run_summary)

    # DEM/elevation contract (only if DEM stage details are present).
    if report_found:
        for report_path in report_candidates:
            if not report_path.is_file():
                continue
            try:
                data = json.loads(report_path.read_text(encoding="utf-8", errors="replace"))
                diagnostics = data.get("diagnostics", {}) if isinstance(data, dict) else {}
                details = diagnostics.get("details", {}) if isinstance(diagnostics, dict) else {}
                if not isinstance(details, dict):
                    continue
                dem_diag = details.get("dem_diagnostics")
                if not isinstance(dem_diag, dict):
                    continue
                dem_exists = dem_diag.get("exists")
                elev_stats = details.get("elevation_stats")
                if dem_exists is True:
                    if not isinstance(elev_stats, dict):
                        fail_validation("DEM enabled but elevation_stats missing", report_path)
                    else:
                        for key in ("mean", "stddev", "count"):
                            if key not in elev_stats:
                                fail_validation(f"elevation_stats missing key: {key}", report_path)
                elif dem_exists is False:
                    dem_disabled = False
                    if isinstance(elev_stats, dict) and elev_stats.get("DEM_disabled") is True:
                        dem_disabled = True
                    if details.get("DEM_disabled") is True:
                        dem_disabled = True
                    if not dem_disabled:
                        fail_validation("DEM disabled but DEM_disabled not recorded explicitly", report_path)
            except Exception as exc:
                fail_validation(f"Failed to validate DEM/elevation contract: {exc}", report_path)

    # If Real_U report exists independently, require core keys.
    if real_u_report.is_file() and not any_gen:
        try:
            data = json.loads(real_u_report.read_text(encoding="utf-8", errors="replace"))
            real = data.get("real", {}) if isinstance(data, dict) else {}
            if not isinstance(real, dict):
                fail_validation("Invalid Real_U report schema: missing real block", real_u_report)
            elif "entropy_mean" not in real or "confidence_mean" not in real:
                fail_validation("Real_U report missing keys entropy_mean/confidence_mean", real_u_report)
        except Exception as exc:
            fail_validation(f"Failed to validate Real_U report: {exc}", real_u_report)


def main():
    parser = argparse.ArgumentParser(description="Validate a CARLA thesis run for QA and reproducibility.")
    parser.add_argument("run_root", type=str, help="Path to the root directory of the thesis run.")
    parser.add_argument("--strict", action="store_true", help="Enable thesis_final strict validation gates.")
    args = parser.parse_args()

    run_root_path = Path(args.run_root).resolve()
    if not run_root_path.is_dir():
        fail_validation("The provided run root is not a valid directory", run_root_path)
        print("\n".join(_VALIDATION_ERRORS), file=sys.stderr)
        sys.exit(1)

    print(f"Starting validation for run root: {run_root_path}")
    strict_mode = bool(args.strict)

    validate_agent_sync_contract()
    validate_bbox_contract(run_root_path, strict_mode)
    if _is_bounded_scenario_b_layout(run_root_path):
        validate_bounded_scenario_b_evidence(run_root_path, strict_mode)
    else:
        validate_determinism_audit(run_root_path)
        validate_comparison_folders(run_root_path, strict_mode)
        validate_perception_evidence_packs(run_root_path, strict_mode)
        validate_xodr_link_integrity(run_root_path, required=True)
    validate_optional_generalization_and_repro(run_root_path, strict_mode)

    if _VALIDATION_ERRORS:
        print("\n".join(_VALIDATION_ERRORS), file=sys.stderr)
        sys.exit(1)

    print("\nAll thesis run validations passed successfully!")
    sys.exit(0)

if __name__ == "__main__":
    main()
