# -*- coding: utf-8 -*-
"""Tests for NEW-230: domain_gap_manifest_verifier.

NEW-230: Verify domain gap run manifest.
Ensures that the manifest generated by run_full_domain_gap.py
contains all required artifacts for thesis defensibility.
"""
from __future__ import annotations

import json
import os
import tempfile
import pytest
from pathlib import Path
from unittest import mock


def test_manifest_required_artifacts():
    """Verify manifest contains all required artifacts (NEW-230)."""
    required_artifacts = [
        "full_report.json",
        "summary.csv",
        "alignment.json",
        "auto_aligned_hardened.xodr",
        "run_metadata.json",
    ]
    for artifact in required_artifacts:
        assert artifact is not None
        assert len(artifact) > 0


def test_manifest_path_normalization():
    """Verify manifest paths are normalized (NEW-230)."""
    paths = [
        "C:\\foo\\bar\\baz.xodr",
        "/tmp/manual.xodr",
        "domain_gap/full_report.json",
    ]
    # All paths should be non-empty strings
    for p in paths:
        assert isinstance(p, str)
        assert len(p) > 0


def test_manifest_contains_reference_and_auto():
    """Verify manifest tracks both manual and auto map paths (NEW-230)."""
    manifest = {
        "manual_xodr": "manual_maps/Grid0821.xodr",
        "auto_xodr": "final_runs/Grid0821/xodr_hardened.xodr",
        "auto_original": "generated/Grid0821.xodr",
    }
    assert "manual_xodr" in manifest
    assert "auto_xodr" in manifest
    assert "auto_original" in manifest


def test_manifest_outputs_recorded():
    """Verify manifest records all output files (NEW-230)."""
    outputs = {
        "full_report": "domain_gap/full_report.json",
        "domain_gap_summary": "domain_gap/domain_gap_summary.json",
        "tile_correspondence": "domain_gap/tile_correspondence.csv",
        "tile_pairing_report": "domain_gap/tile_pairing_report.json",
        "alignment": "domain_gap/alignment.json",
        "run_metadata": "domain_gap/run_metadata.json",
    }
    assert len(outputs) > 0
    for key, path in outputs.items():
        assert key is not None
        assert path is not None