#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FBX round-trip import (Phase J6)
Auto-generated by fbx_roundtrip.py
"""
import bpy
import sys
import json

def main():
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        print("ERROR: No arguments passed after '--'", flush=True)
        sys.exit(1)
    if len(argv) < 2:
        print("ERROR: Expected: input.fbx manifest.json", flush=True)
        sys.exit(1)
    input_fbx, manifest_path = argv[0], argv[1]

    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        bpy.ops.preferences.addon_enable(module="io_scene_fbx")
    except Exception as e:
        print(f"[RT] WARN addon: {e}", flush=True)
    print(f"[RT] Importing FBX: {input_fbx}", flush=True)
    try:
        bpy.ops.import_scene.fbx(
            filepath=input_fbx,
            global_scale=1.0,
            axis_forward='-Z',
            axis_up='Y',
        )
        print("[RT] FBX import successful", flush=True)
    except Exception as e:
        print(f"[RT] ERROR importing FBX: {e}", flush=True)
        sys.exit(1)

    manifest = {
        "blender_version": bpy.app.version_string,
        "import_operator": "import_scene.fbx",
        "import_options": {
            "filepath": input_fbx,
            "global_scale": 1.0,
            "axis_forward": "-Z",
            "axis_up": "Y",
        },
    }
    mesh_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    inventory = []
    for o in mesh_objects:
        mesh = o.data
        mats = [m.name for m in mesh.materials if m]
        bounds = [[round(c, 6) for c in corner] for corner in o.bound_box]
        inventory.append({
            "name": o.name,
            "type": o.type,
            "vertices": len(mesh.vertices),
            "faces": len(mesh.polygons),
            "uv_layers": len(mesh.uv_layers),
            "materials": mats,
            "bounds": bounds,
        })
    manifest["objects"] = inventory
    manifest["objects_total"] = len(mesh_objects)
    manifest["materials_total"] = len(bpy.data.materials)

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print("[RT] ROUNDTRIP_OK", flush=True)
    sys.exit(0)

if __name__ == "__main__":
    main()
